import { defineWorkspace } from 'vitest/config';

const BROWSER_MODE_READY_COMPONENTS = [
    'accordion',
    'accordion-item',
    'action-group',
    'alert',
    'audio-player.fixit',
    'avatar', 
    'badge', 
    'banner', 
    'breadcrumb', 
    'breadcrumb-item',
    'button',
    'calendar',
    'calendar-event',
    'card',
    'checkbox',
    'combobox.fixit',
    'data-grid.fixit',
    'data-grid-cell',
    'data-grid-row', 
    'date-picker.fixit',
    'date-range-picker.fixit',
    'dial-pad.fixit',
    'dialog.fixit',
    'divider',
    'elevation',
    'empty-state',
    'fab',
    'file-picker',
    'header',
    'icon.fixit',
    'layout',
    'menu.fixit',
    'menu-item.fixit',
    'nav',
    'nav-disclosure.flaky',
    'nav-item',
    'note',
    'number-field',
    'option',
    'pagination',
    'popup.fixit',
    'progress',
    'progress-ring.fixit',
    'radio',
    'radio-group',
    'range-slider.fixit',
    'rich-text-editor',
    'searchable-select',
    'select.fixit',
    'selectable-box.fixit',
    'side-drawer',
    'slider.fixit',
    'split-button.fixit',
    'switch',
    'tab',
    'tab-panel',
    'tabs.fixit',
    'tag',
    'tag-group',
    'text-anchor',
    'text-area.fixit',
    'text-field.fixit',
    'time-picker.fixit',
    'toggletip',
    'tooltip',
    'tree-item',
    'tree-view',
    'video-player',
    ].map((component) => `libs/components/src/**/${component}.spec.ts`);

const isCI = process.env['CI'] === 'true';
const isA11y = process.env['A11Y'] === 'true';

export default defineWorkspace([
    {
        extends: 'vite.config.ts',
        test: {
            name: 'jsdom',
            globals: true,
            environment: 'jsdom',
            include: ['libs/components/src/**/*.spec.ts'],
            exclude: BROWSER_MODE_READY_COMPONENTS,
            setupFiles: ['libs/components/vitest.a11y.setup.ts'],
        },
    },
    {
        extends: 'vite.config.ts',
        test: {
            name: 'browser',
            globals: true,
            include: BROWSER_MODE_READY_COMPONENTS,
            setupFiles: ['libs/components/vitest.setup.ts'],
            coverage: {
                reportsDirectory: '../../coverage/libs/components',
                provider: 'v8',
                include: ['src/**/*.ts'],
                exclude: ['src/**/*.spec.ts', 'src/**/*test*.ts', 'src/locales/**.*'],
                reporter: isCI
                    ? ['lcov', 'text']
                    : ['text', 'html', 'clover', 'json', 'lcov'],
            },
            browser: {
                name: 'chromium',
                provider: 'playwright',
                headless: isCI,
                enabled: true,
                instances: [
                    { browser: 'chromium' },
                ],
            },
        },
    }
]);