codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "95...100"
  status:
    project:
      default:
        target: 95%
        threshold: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

