packages:
  - apps/*
  - libs/*
  - turbo/generators

catalog:
  '@custom-elements-manifest/analyzer': ^0.5.7
  '@microsoft/eslint-config-fast-dna': ^2.1.0
  '@microsoft/fast-element': 2.8.3
  '@microsoft/fast-foundation': ^2.50.0
  '@microsoft/fast-web-utilities': ^6.0.0
  '@playwright/test': 1.57.0
  '@types/eslint': ^8.56.12
  '@types/jsdom': ^21.1.7
  '@types/markdown-it': ^13.0.9
  '@types/markdown-table': ^2.0.0
  '@types/node': ^20.19.25
  '@typescript-eslint/eslint-plugin': 7.18.0
  '@typescript-eslint/parser': 7.18.0
  '@typescript-eslint/utils': 7.18.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  cem-plugin-async-function: ^0.0.5
  cem-plugin-jsdoc-example: ^0.0.9
  cem-plugin-jsdoc-function: ^0.0.5
  cem-plugin-readonly: ^0.0.5
  concurrently: ^9.2.1
  custom-elements-manifest: ^2.1.0
  cypress: ^14.5.4
  esbuild: ^0.25.12
  eslint: 9.26.0
  eslint-config-prettier: 9.1.2
  eslint-plugin-ban: ^1.6.0
  eslint-plugin-compat: ^4.2.0
  eslint-plugin-import: ^2.32.0
  eslint-plugin-tsdoc: ^0.4.0
  eslint-plugin-unused-imports: ^3.2.0
  eslint-plugin-vue: ^9.33.0
  istanbul-merge: ^2.0.0
  jsdom: ^23.2.0
  markdown-it: ^13.0.2
  markdown-it-anchor: ^8.6.7
  markdown-table: ^2.0.0
  nyc: ^17.1.0
  playwright: 1.57.0
  prettier: 2.8.8
  prettier-plugin-packagejson: ^2.5.19
  sass: ^1.94.2
  stylelint: ^16.25.0
  stylelint-config-idiomatic-order: ^10.0.0
  stylelint-config-standard-scss: ^15.0.1
  stylelint-no-unsupported-browser-features: ^8.0.5
  tsx: ^4.20.6
  typescript: 5.9.3
  vite: ^5.4.18
  vite-plugin-dts: ~2.3.0
  vite-plugin-static-copy: ^1.0.6
  vitest: ^3.2.4
  vitest-axe: ^0.1.0
  vitest-fetch-mock: ^0.4.5

catalogs:
  vue2:
    vue: ^2.7.16
  vue3:
    vue: ^3.5.24
    vue3: npm:vue@^3.5.24

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - cypress
  - esbuild

overrides:
  braces: 3.0.3
  minimist: 1.2.8
  nconf: 0.13.0
  path-to-regexp: 0.2.5
