ServerName localhost
Listen {{PORT}}

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule alias_module modules/mod_alias.so
LoadModule env_module modules/mod_env.so
LoadModule log_config_module modules/mod_log_config.so

User www-data
Group www-data

SetEnv GIT_PROJECT_ROOT /repos
SetEnv GIT_HTTP_EXPORT_ALL
SetEnv REMOTE_USER anonymous

ScriptAlias / /usr/libexec/git-core/git-http-backend/

<Directory "/usr/libexec/git-core">
    Options +ExecCGI
    Require all granted
</Directory>

ErrorLog /dev/stderr
CustomLog /dev/stdout combined
LogLevel warn
