name: create-version-tag
description: Creates a git tag for a given version and sha.
branding:
  color: purple

inputs:
  tag:
    description: The name of the tag to create
    required: true
  version:
    description: The version to create the tag for
    required: true
  sha:
    description: The sha to create the tag on
    required: false
    default: ${{ github.sha }}
  token:
    description: The github token for automation
    required: false
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Create Tag ${{ inputs.tag }}-v${{ inputs.version }}
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.token }}
        script: |
          await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag }}-v${{ inputs.version }}',
              sha: '${{ inputs.sha }}'
          })
