export interface Country {
	code: string;
	label?: string;
	countryCode?: string;
	iconFlagName?: string;
}

/** Country list from https://github.com/esmat-nawahda/countries (countries.ts). */
export const countries: Country[] = [
	{
		code: 'AF',
		label: 'Afghanistan',
		countryCode: '+93',
		iconFlagName: 'flag-afghanistan',
	},
	{
		code: 'AL',
		label: 'Albania',
		countryCode: '+355',
		iconFlagName: 'flag-albania',
	},
	{
		code: 'DZ',
		label: 'Algeria',
		countryCode: '+213',
		iconFlagName: 'flag-algeria',
	},
	{ code: 'AS', label: 'American Samoa', countryCode: '+1', iconFlagName: '' },
	{ code: 'AD', label: 'Andorra', countryCode: '+376', iconFlagName: '' },
	{ code: 'AO', label: 'Angola', countryCode: '+244', iconFlagName: '' },
	{ code: 'AI', label: 'Anguilla', countryCode: '+43', iconFlagName: '' },
	{
		code: 'AG',
		label: 'Antigua and Barbuda',
		countryCode: '+1',
		iconFlagName: '',
	},
	{
		code: 'AR',
		label: 'Argentina',
		countryCode: '+54',
		iconFlagName: 'flag-argentina',
	},
	{
		code: 'AM',
		label: 'Armenia',
		countryCode: '+374',
		iconFlagName: 'flag-armenia',
	},
	{
		code: 'AW',
		label: 'Aruba',
		countryCode: '+297',
		iconFlagName: 'flag-aruba',
	},
	{
		code: 'AU',
		label: 'Australia',
		countryCode: '+61',
		iconFlagName: 'flag-australia',
	},
	{
		code: 'AT',
		label: 'Austria',
		countryCode: '+43',
		iconFlagName: 'flag-austria',
	},
	{ code: 'AZ', label: 'Azerbaijan', countryCode: '+994', iconFlagName: '' },
	{
		code: 'BS',
		label: 'Bahamas',
		countryCode: '+1',
		iconFlagName: 'flag-bahamas',
	},
	{
		code: 'BH',
		label: 'Bahrain',
		countryCode: '+973',
		iconFlagName: 'flag-bahrain',
	},
	{
		code: 'BD',
		label: 'Bangladesh',
		countryCode: '+880',
		iconFlagName: 'flag-bangladesh',
	},
	{ code: 'BB', label: 'Barbados', countryCode: '+1', iconFlagName: '' },
	{
		code: 'BY',
		label: 'Belarus',
		countryCode: '+375',
		iconFlagName: 'flag-belarus',
	},
	{
		code: 'BE',
		label: 'Belgium',
		countryCode: '+32',
		iconFlagName: 'flag-belgium',
	},
	{ code: 'BZ', label: 'Belize', countryCode: '+501', iconFlagName: '' },
	{
		code: 'BJ',
		label: 'Benin',
		countryCode: '+229',
		iconFlagName: 'flag-benin',
	},
	{ code: 'BM', label: 'Bermuda', countryCode: '+1', iconFlagName: '' },
	{ code: 'BT', label: 'Bhutan', countryCode: '+975', iconFlagName: '' },
	{
		code: 'BO',
		label: 'Bolivia (Plurinational State of)',
		countryCode: '+591',
		iconFlagName: 'flag-bolivia',
	},
	{
		code: 'BA',
		label: 'Bosnia and Herzegovina',
		countryCode: '+387',
		iconFlagName: '',
	},
	{
		code: 'BW',
		label: 'Botswana',
		countryCode: '+267',
		iconFlagName: 'flag-botswana',
	},
	{
		code: 'BR',
		label: 'Brazil',
		countryCode: '+55',
		iconFlagName: 'flag-brazil',
	},
	{
		code: 'IO',
		label: 'British Indian Ocean Territory',
		countryCode: '+246',
		iconFlagName: '',
	},
	{
		code: 'VG',
		label: 'Virgin Islands (British)',
		countryCode: '+1',
		iconFlagName: '',
	},
	{
		code: 'VI',
		label: 'Virgin Islands (U.S.)',
		countryCode: '+1',
		iconFlagName: '',
	},
	{
		code: 'BN',
		label: 'Brunei Darussalam',
		countryCode: '+673',
		iconFlagName: '',
	},
	{
		code: 'BG',
		label: 'Bulgaria',
		countryCode: '+359',
		iconFlagName: 'flag-bulgaria',
	},
	{
		code: 'BF',
		label: 'Burkina Faso',
		countryCode: '+226',
		iconFlagName: 'flag-burkina-faso',
	},
	{ code: 'BI', label: 'Burundi', countryCode: '+257', iconFlagName: '' },
	{
		code: 'KH',
		label: 'Cambodia',
		countryCode: '+855',
		iconFlagName: 'flag-cambodia',
	},
	{ code: 'CM', label: 'Cameroon', countryCode: '+237', iconFlagName: '' },
	{
		code: 'CA',
		label: 'Canada',
		countryCode: '+1',
		iconFlagName: 'flag-canada',
	},
	{ code: 'CV', label: 'Cabo Verde', countryCode: '+238', iconFlagName: '' },
	{
		code: 'KY',
		label: 'Cayman Islands',
		countryCode: '+1',
		iconFlagName: 'flag-cayman-islands',
	},
	{
		code: 'CF',
		label: 'Central African Republic',
		countryCode: '+236',
		iconFlagName: 'flag-central-african-republic',
	},
	{
		code: 'CF',
		label: 'Central African Republic',
		countryCode: '+236',
		iconFlagName: 'flag-central-african-republic',
	},
	{
		code: 'CL',
		label: 'Chile',
		countryCode: '+56',
		iconFlagName: 'flag-chile',
	},
	{
		code: 'CN',
		label: 'China',
		countryCode: '+86',
		iconFlagName: 'flag-china',
	},
	{
		code: 'CO',
		label: 'Colombia',
		countryCode: '+57',
		iconFlagName: 'flag-colombia',
	},
	{ code: 'KM', label: 'Comoros', countryCode: '+269', iconFlagName: '' },
	{ code: 'CG', label: 'Congo', countryCode: '+242', iconFlagName: '' },
	{
		code: 'CD',
		label: 'Congo (Democratic Republic of the)',
		countryCode: '+243',
		iconFlagName: '',
	},
	{ code: 'CK', label: 'Cook Islands', countryCode: '+682', iconFlagName: '' },
	{
		code: 'CR',
		label: 'Costa Rica',
		countryCode: '+506',
		iconFlagName: 'flag-costa-rica',
	},
	{
		code: 'HR',
		label: 'Croatia',
		countryCode: '+385',
		iconFlagName: 'flag-croatia',
	},
	{ code: 'CU', label: 'Cuba', countryCode: '+53', iconFlagName: '' },
	{ code: 'CU', label: 'Cuba', countryCode: '+53', iconFlagName: '' },
	{
		code: 'CY',
		label: 'Cyprus',
		countryCode: '+357',
		iconFlagName: 'flag-cyprus',
	},
	{
		code: 'CZ',
		label: 'Czech Republic',
		countryCode: '+420',
		iconFlagName: 'flag-czech-republic',
	},
	{
		code: 'DK',
		label: 'Denmark',
		countryCode: '+45',
		iconFlagName: 'flag-denmark',
	},
	{ code: 'DJ', label: 'Djibouti', countryCode: '+253', iconFlagName: '' },
	{ code: 'DM', label: 'Dominica', countryCode: '+1', iconFlagName: '' },
	{
		code: 'DO',
		label: 'Dominican Republic',
		countryCode: '+1',
		iconFlagName: 'flag-dominican-republic',
	},
	{ code: 'EC', label: 'Ecuador', countryCode: '+593', iconFlagName: '' },
	{
		code: 'EG',
		label: 'Egypt',
		countryCode: '+20',
		iconFlagName: 'flag-egypt',
	},
	{
		code: 'SV',
		label: 'El Salvador',
		countryCode: '+503',
		iconFlagName: 'flag-el-salvador',
	},
	{
		code: 'GQ',
		label: 'Equatorial Guinea',
		countryCode: '+240',
		iconFlagName: '',
	},
	{ code: 'ER', label: 'Eritrea', countryCode: '+291', iconFlagName: '' },
	{
		code: 'EE',
		label: 'Estonia',
		countryCode: '+372',
		iconFlagName: 'flag-estonia',
	},
	{ code: 'ET', label: 'Ethiopia', countryCode: '+251', iconFlagName: '' },
	{
		code: 'FK',
		label: 'Falkland Islands (Malvinas)',
		countryCode: '+500',
		iconFlagName: '',
	},
	{ code: 'FO', label: 'Faroe Islands', countryCode: '+298', iconFlagName: '' },
	{ code: 'FJ', label: 'Fiji', countryCode: '+679', iconFlagName: '' },
	{
		code: 'FI',
		label: 'Finland',
		countryCode: '+358',
		iconFlagName: 'flag-finland',
	},
	{
		code: 'FR',
		label: 'France',
		countryCode: '+33',
		iconFlagName: 'flag-france',
	},
	{ code: 'GF', label: 'French Guiana', countryCode: '+594', iconFlagName: '' },
	{
		code: 'PF',
		label: 'French Polynesia',
		countryCode: '+689',
		iconFlagName: '',
	},
	{ code: 'GA', label: 'Gabon', countryCode: '+241', iconFlagName: '' },
	{ code: 'GM', label: 'Gambia', countryCode: '+220', iconFlagName: '' },
	{
		code: 'GE',
		label: 'Georgia',
		countryCode: '+995',
		iconFlagName: 'flag-georgia',
	},
	{
		code: 'DE',
		label: 'Germany',
		countryCode: '+49',
		iconFlagName: 'flag-germany',
	},
	{
		code: 'GH',
		label: 'Ghana',
		countryCode: '+233',
		iconFlagName: 'flag-ghana',
	},
	{ code: 'GI', label: 'Gibraltar', countryCode: '+350', iconFlagName: '' },
	{
		code: 'GR',
		label: 'Greece',
		countryCode: '+30',
		iconFlagName: 'flag-greece',
	},
	{ code: 'GL', label: 'Greenland', countryCode: '+299', iconFlagName: '' },
	{
		code: 'GD',
		label: 'Grenada',
		countryCode: '+1',
		iconFlagName: 'flag-grenada',
	},
	{ code: 'GP', label: 'Guadeloupe', countryCode: '+590', iconFlagName: '' },
	{ code: 'GU', label: 'Guam', countryCode: '+1', iconFlagName: '' },
	{
		code: 'GT',
		label: 'Guatemala',
		countryCode: '+502',
		iconFlagName: 'flag-guatemala',
	},
	{ code: 'GN', label: 'Guinea', countryCode: '+224', iconFlagName: '' },
	{ code: 'GW', label: 'Guinea-Bissau', countryCode: '+245', iconFlagName: '' },
	{ code: 'GY', label: 'Guyana', countryCode: '+592', iconFlagName: '' },
	{ code: 'HT', label: 'Haiti', countryCode: '+509', iconFlagName: '' },
	{ code: 'VA', label: 'Holy See', countryCode: '+39', iconFlagName: '' },
	{
		code: 'HN',
		label: 'Honduras',
		countryCode: '+504',
		iconFlagName: 'flag-honduras',
	},
	{
		code: 'HK',
		label: 'Hong Kong',
		countryCode: '+852',
		iconFlagName: 'flag-hong-kong',
	},
	{
		code: 'HU',
		label: 'Hungary',
		countryCode: '+36',
		iconFlagName: 'flag-hungary',
	},
	{
		code: 'IS',
		label: 'Iceland',
		countryCode: '+354',
		iconFlagName: 'flag-iceland',
	},
	{
		code: 'IN',
		label: 'India',
		countryCode: '+91',
		iconFlagName: 'flag-india',
	},
	{
		code: 'ID',
		label: 'Indonesia',
		countryCode: '+62',
		iconFlagName: 'flag-indonesia',
	},
	{ code: 'CI', label: "Côte d'Ivoire", countryCode: '+225', iconFlagName: '' },
	{
		code: 'IR',
		label: 'Iran (Islamic Republic of)',
		countryCode: '+98',
		iconFlagName: '',
	},
	{ code: 'IQ', label: 'Iraq', countryCode: '+964', iconFlagName: '' },
	{
		code: 'IE',
		label: 'Ireland',
		countryCode: '+353',
		iconFlagName: 'flag-ireland',
	},
	{
		code: 'IL',
		label: 'Israel',
		countryCode: '+972',
		iconFlagName: 'flag-israel',
	},
	{
		code: 'IT',
		label: 'Italy',
		countryCode: '+39',
		iconFlagName: 'flag-italy',
	},
	{
		code: 'JM',
		label: 'Jamaica',
		countryCode: '+1',
		iconFlagName: 'flag-jamaica',
	},
	{
		code: 'JP',
		label: 'Japan',
		countryCode: '+81',
		iconFlagName: 'flag-japan',
	},
	{ code: 'JO', label: 'Jordan', countryCode: '+962', iconFlagName: '' },
	{ code: 'KZ', label: 'Kazakhstan', countryCode: '+7', iconFlagName: '' },
	{ code: 'KE', label: 'Kenya', countryCode: '+254', iconFlagName: '' },
	{ code: 'KI', label: 'Kiribati', countryCode: '+686', iconFlagName: '' },
	{ code: 'KW', label: 'Kuwait', countryCode: '+965', iconFlagName: '' },
	{ code: 'KG', label: 'Kyrgyzstan', countryCode: '+996', iconFlagName: '' },
	{
		code: 'LA',
		label: "Lao People's Democratic Republic",
		countryCode: '+856',
		iconFlagName: '',
	},
	{
		code: 'LV',
		label: 'Latvia',
		countryCode: '+371',
		iconFlagName: 'flag-latvia',
	},
	{ code: 'LB', label: 'Lebanon', countryCode: '+961', iconFlagName: '' },
	{ code: 'LS', label: 'Lesotho', countryCode: '+266', iconFlagName: '' },
	{ code: 'LR', label: 'Liberia', countryCode: '+231', iconFlagName: '' },
	{ code: 'LY', label: 'Libya', countryCode: '+218', iconFlagName: '' },
	{
		code: 'LI',
		label: 'Liechtenstein',
		countryCode: '+423',
		iconFlagName: 'flag-liechtenstein',
	},
	{
		code: 'LT',
		label: 'Lithuania',
		countryCode: '+370',
		iconFlagName: 'flag-lithuania',
	},
	{
		code: 'LU',
		label: 'Luxembourg',
		countryCode: '+352',
		iconFlagName: 'flag-luxembourg',
	},
	{
		code: 'MO',
		label: 'Macao',
		countryCode: '+853',
		iconFlagName: 'flag-macao',
	},
	{
		code: 'MK',
		label: 'Macedonia (the former Yugoslav Republic of)',
		countryCode: '+389',
		iconFlagName: '',
	},
	{ code: 'MG', label: 'Madagascar', countryCode: '+261', iconFlagName: '' },
	{ code: 'MW', label: 'Malawi', countryCode: '+265', iconFlagName: '' },
	{
		code: 'MY',
		label: 'Malaysia',
		countryCode: '+60',
		iconFlagName: 'flag-malaysia',
	},
	{ code: 'MV', label: 'Maldives', countryCode: '+960', iconFlagName: '' },
	{ code: 'ML', label: 'Mali', countryCode: '+223', iconFlagName: '' },
	{
		code: 'MT',
		label: 'Malta',
		countryCode: '+356',
		iconFlagName: 'flag-malta',
	},
	{
		code: 'MH',
		label: 'Marshall Islands',
		countryCode: '+692',
		iconFlagName: '',
	},
	{ code: 'MQ', label: 'Martinique', countryCode: '+596', iconFlagName: '' },
	{ code: 'MR', label: 'Mauritania', countryCode: '+222', iconFlagName: '' },
	{
		code: 'MU',
		label: 'Mauritius',
		countryCode: '+230',
		iconFlagName: 'flag-mauritius',
	},
	{ code: 'YT', label: 'Mayotte', countryCode: '+262', iconFlagName: '' },
	{
		code: 'MX',
		label: 'Mexico',
		countryCode: '+52',
		iconFlagName: 'flag-mexico',
	},
	{
		code: 'FM',
		label: 'Micronesia (Federated States of)',
		countryCode: '+691',
		iconFlagName: '',
	},
	{
		code: 'MD',
		label: 'Moldova (Republic of)',
		countryCode: '+373',
		iconFlagName: 'flag-moldova',
	},
	{ code: 'MC', label: 'Monaco', countryCode: '+377', iconFlagName: '' },
	{ code: 'MN', label: 'Mongolia', countryCode: '+976', iconFlagName: '' },
	{ code: 'ME', label: 'Montenegro', countryCode: '+382', iconFlagName: '' },
	{ code: 'MS', label: 'Montserrat', countryCode: '+1', iconFlagName: '' },
	{ code: 'MA', label: 'Morocco', countryCode: '+212', iconFlagName: '' },
	{ code: 'MZ', label: 'Mozambique', countryCode: '+258', iconFlagName: '' },
	{ code: 'MM', label: 'Myanmar', countryCode: '+95', iconFlagName: '' },
	{ code: 'NA', label: 'Namibia', countryCode: '+264', iconFlagName: '' },
	{ code: 'NR', label: 'Nauru', countryCode: '+674', iconFlagName: '' },
	{ code: 'NP', label: 'Nepal', countryCode: '+977', iconFlagName: '' },
	{
		code: 'NL',
		label: 'Netherlands',
		countryCode: '+31',
		iconFlagName: 'flag-netherlands',
	},
	{ code: 'NC', label: 'New Caledonia', countryCode: '+687', iconFlagName: '' },
	{
		code: 'NZ',
		label: 'New Zealand',
		countryCode: '+64',
		iconFlagName: 'flag-new-zealand',
	},
	{ code: 'NI', label: 'Nicaragua', countryCode: '+505', iconFlagName: '' },
	{ code: 'NE', label: 'Niger', countryCode: '+227', iconFlagName: '' },
	{
		code: 'NG',
		label: 'Nigeria',
		countryCode: '+234',
		iconFlagName: 'flag-nigeria',
	},
	{ code: 'NU', label: 'Niue', countryCode: '+683', iconFlagName: '' },
	{
		code: 'NF',
		label: 'Norfolk Island',
		countryCode: '+672',
		iconFlagName: '',
	},
	{
		code: 'KP',
		label: "Korea (Democratic People's Republic of)",
		countryCode: '+850',
		iconFlagName: '',
	},
	{
		code: 'MP',
		label: 'Northern Mariana Islands',
		countryCode: '+1',
		iconFlagName: '',
	},
	{
		code: 'NO',
		label: 'Norway',
		countryCode: '+47',
		iconFlagName: 'flag-norway',
	},
	{ code: 'OM', label: 'Oman', countryCode: '+968', iconFlagName: '' },
	{
		code: 'PK',
		label: 'Pakistan',
		countryCode: '+92',
		iconFlagName: 'flag-pakistan',
	},
	{ code: 'PW', label: 'Palau', countryCode: '+680', iconFlagName: '' },
	{ code: 'PS', label: 'Palestine', countryCode: '+970', iconFlagName: '' },
	{
		code: 'PA',
		label: 'Panama',
		countryCode: '+507',
		iconFlagName: 'flag-panama',
	},
	{
		code: 'PG',
		label: 'Papua New Guinea',
		countryCode: '+675',
		iconFlagName: '',
	},
	{ code: 'PY', label: 'Paraguay', countryCode: '+595', iconFlagName: '' },
	{ code: 'PE', label: 'Peru', countryCode: '+51', iconFlagName: 'flag-peru' },
	{
		code: 'PH',
		label: 'Philippines',
		countryCode: '+63',
		iconFlagName: 'flag-philippines',
	},
	{
		code: 'PL',
		label: 'Poland',
		countryCode: '+48',
		iconFlagName: 'flag-poland',
	},
	{
		code: 'PT',
		label: 'Portugal',
		countryCode: '+351',
		iconFlagName: 'flag-portugal',
	},
	{
		code: 'PR',
		label: 'Puerto Rico',
		countryCode: '+1',
		iconFlagName: 'flag-puertorico',
	},
	{ code: 'QA', label: 'Qatar', countryCode: '+974', iconFlagName: '' },
	{
		code: 'XK',
		label: 'Republic of Kosovo',
		countryCode: '+381',
		iconFlagName: '',
	},
	{ code: 'RE', label: 'Réunion', countryCode: '+262', iconFlagName: '' },
	{
		code: 'RO',
		label: 'Romania',
		countryCode: '+40',
		iconFlagName: 'flag-romania',
	},
	{
		code: 'RU',
		label: 'Russian Federation',
		countryCode: '+7',
		iconFlagName: 'flag-russia',
	},
	{
		code: 'RW',
		label: 'Rwanda',
		countryCode: '+250',
		iconFlagName: 'flag-rwanda',
	},
	{
		code: 'BL',
		label: 'Saint Barthélemy',
		countryCode: '+590',
		iconFlagName: '',
	},
	{
		code: 'SH',
		label: 'Saint Helena, Ascension and Tristan da Cunha',
		countryCode: '+290',
		iconFlagName: '',
	},
	{
		code: 'KN',
		label: 'Saint Kitts and Nevis',
		countryCode: '+1',
		iconFlagName: '',
	},
	{ code: 'LC', label: 'Saint Lucia', countryCode: '+1', iconFlagName: '' },
	{
		code: 'MF',
		label: 'Saint Martin (French part)',
		countryCode: '+590',
		iconFlagName: '',
	},
	{
		code: 'PM',
		label: 'Saint Pierre and Miquelon',
		countryCode: '+508',
		iconFlagName: '',
	},
	{
		code: 'VC',
		label: 'Saint Vincent and the Grenadines',
		countryCode: '+1',
		iconFlagName: '',
	},
	{ code: 'WS', label: 'Samoa', countryCode: '+685', iconFlagName: '' },
	{ code: 'SM', label: 'San Marino', countryCode: '+378', iconFlagName: '' },
	{
		code: 'ST',
		label: 'Sao Tome and Principe',
		countryCode: '+239',
		iconFlagName: '',
	},
	{
		code: 'SA',
		label: 'Saudi Arabia',
		countryCode: '+966',
		iconFlagName: 'flag-saudi-arabia',
	},
	{ code: 'SN', label: 'Senegal', countryCode: '+221', iconFlagName: '' },
	{
		code: 'RS',
		label: 'Serbia',
		countryCode: '+381',
		iconFlagName: 'flag-serbia',
	},
	{ code: 'SC', label: 'Seychelles', countryCode: '+248', iconFlagName: '' },
	{ code: 'SL', label: 'Sierra Leone', countryCode: '+232', iconFlagName: '' },
	{
		code: 'SG',
		label: 'Singapore',
		countryCode: '+65',
		iconFlagName: 'flag-singapore',
	},
	{
		code: 'SG',
		label: 'Singapore',
		countryCode: '+65',
		iconFlagName: 'flag-singapore',
	},
	{
		code: 'SK',
		label: 'Slovakia',
		countryCode: '+421',
		iconFlagName: 'flag-slovakia',
	},
	{
		code: 'SI',
		label: 'Slovenia',
		countryCode: '+386',
		iconFlagName: 'flag-slovenia',
	},
	{
		code: 'SB',
		label: 'Solomon Islands',
		countryCode: '+677',
		iconFlagName: '',
	},
	{ code: 'SO', label: 'Somalia', countryCode: '+252', iconFlagName: '' },
	{
		code: 'ZA',
		label: 'South Africa',
		countryCode: '+27',
		iconFlagName: 'flag-south-africa',
	},
	{
		code: 'KR',
		label: 'Korea (Republic of)',
		countryCode: '+82',
		iconFlagName: 'flag-south-korea',
	},
	{
		code: 'ES',
		label: 'Spain',
		countryCode: '+34',
		iconFlagName: 'flag-spain',
	},
	{
		code: 'LK',
		label: 'Sri Lanka',
		countryCode: '+94',
		iconFlagName: 'flag-sri-lanka',
	},
	{ code: 'SD', label: 'Sudan', countryCode: '+249', iconFlagName: '' },
	{ code: 'SR', label: 'Suriname', countryCode: '+597', iconFlagName: '' },
	{ code: 'SZ', label: 'Swaziland', countryCode: '+268', iconFlagName: '' },
	{
		code: 'SE',
		label: 'Sweden',
		countryCode: '+46',
		iconFlagName: 'flag-sweden',
	},
	{
		code: 'CH',
		label: 'Switzerland',
		countryCode: '+41',
		iconFlagName: 'flag-switzerland',
	},
	{
		code: 'SY',
		label: 'Syrian Arab Republic',
		countryCode: '+963',
		iconFlagName: '',
	},
	{
		code: 'TW',
		label: 'Taiwan',
		countryCode: '+886',
		iconFlagName: 'flag-taiwan',
	},
	{
		code: 'TJ',
		label: 'Tajikistan',
		countryCode: '+992',
		iconFlagName: 'flag-tajikistan',
	},
	{
		code: 'TZ',
		label: 'Tanzania, United Republic of',
		countryCode: '+255',
		iconFlagName: 'flag-tanzania',
	},
	{
		code: 'TH',
		label: 'Thailand',
		countryCode: '+66',
		iconFlagName: 'flag-thailand',
	},
	{ code: 'TL', label: 'Timor-Leste', countryCode: '+670', iconFlagName: '' },
	{ code: 'TG', label: 'Togo', countryCode: '+228', iconFlagName: '' },
	{ code: 'TK', label: 'Tokelau', countryCode: '+690', iconFlagName: '' },
	{ code: 'TO', label: 'Tonga', countryCode: '+676', iconFlagName: '' },
	{
		code: 'TT',
		label: 'Trinidad and Tobago',
		countryCode: '+1',
		iconFlagName: 'flag-trinidad-and-tobago',
	},
	{ code: 'TN', label: 'Tunisia', countryCode: '+216', iconFlagName: '' },
	{
		code: 'TR',
		label: 'Turkey',
		countryCode: '+90',
		iconFlagName: 'flag-turkey',
	},
	{ code: 'TM', label: 'Turkmenistan', countryCode: '+993', iconFlagName: '' },
	{
		code: 'TC',
		label: 'Turks and Caicos Islands',
		countryCode: '+1',
		iconFlagName: '',
	},
	{ code: 'TV', label: 'Tuvalu', countryCode: '+688', iconFlagName: '' },
	{ code: 'UG', label: 'Uganda', countryCode: '+256', iconFlagName: '' },
	{
		code: 'UA',
		label: 'Ukraine',
		countryCode: '+380',
		iconFlagName: 'flag-ukraine',
	},
	{
		code: 'AE',
		label: 'United Arab Emirates',
		countryCode: '+971',
		iconFlagName: 'flag-united-arab-emirates',
	},
	{
		code: 'GB',
		label: 'United Kingdom of Great Britain and Northern Ireland',
		countryCode: '+44',
		iconFlagName: 'flag-united-kingdom',
	},
	{
		code: 'UK',
		label: 'United Kingdom',
		countryCode: '+44',
		iconFlagName: 'flag-united-kingdom',
	},
	{
		code: 'US',
		label: 'United States of America',
		countryCode: '+1',
		iconFlagName: 'flag-united-states',
	},
	{
		code: 'UY',
		label: 'Uruguay',
		countryCode: '+598',
		iconFlagName: 'flag-uruguay',
	},
	{
		code: 'UZ',
		label: 'Uzbekistan',
		countryCode: '+998',
		iconFlagName: 'flag-uzbekistan',
	},
	{ code: 'VU', label: 'Vanuatu', countryCode: '+678', iconFlagName: '' },
	{
		code: 'VE',
		label: 'Venezuela (Bolivarian Republic of)',
		countryCode: '+58',
		iconFlagName: 'flag-venezuela',
	},
	{
		code: 'VN',
		label: 'Viet Nam',
		countryCode: '+84',
		iconFlagName: 'flag-vietnam',
	},
	{
		code: 'WF',
		label: 'Wallis and Futuna',
		countryCode: '+681',
		iconFlagName: '',
	},
	{
		code: 'WF',
		label: 'Wallis and Futuna',
		countryCode: '+681',
		iconFlagName: '',
	},
	{ code: 'YE', label: 'Yemen', countryCode: '+967', iconFlagName: '' },
	{
		code: 'ZM',
		label: 'Zambia',
		countryCode: '+260',
		iconFlagName: 'flag-zambia',
	},
	{ code: 'ZW', label: 'Zimbabwe', countryCode: '+263', iconFlagName: '' },
];
