/**
 * Country structure
 * @internal
 */
export interface Country {
	label: string;
	code: string;
	alpha2?: string;
	alpha3?: string;
	capital: string;
	region: string;
	currency: {
		code: string;
		label: string;
		symbol: string | null;
	};
	language: any;
	iconFlagName: string;
	countryCode: string;
	isoCode: string;
	demonym?: string;
	timezone?: string[];
	coordinates?: {
		latitude: number;
		longitude: number;
	};
	area?: number;
	population?: number;
	borderCountries?: string[];
	nativeName?: string;
	subregion?: string;
}

/** Country list from https://github.com/esmat-nawahda/countries (countries.ts). */
export const countries: Country[] = [
	{
		label: 'Afghanistan',
		code: 'AF',
		capital: 'Kabul',
		region: 'AS',
		currency: {
			code: 'AFN',
			label: 'Afghan afghani',
			symbol: '؋',
		},
		language: {
			code: 'ps',
			label: 'Pashto',
		},
		iconFlagName: 'flag-afghanistan',
		countryCode: '+93',
		isoCode: '004',
	},
	{
		label: 'Albania',
		code: 'AL',
		capital: 'Tirana',
		region: 'EU',
		currency: {
			code: 'ALL',
			label: 'Albanian lek',
			symbol: 'L',
		},
		language: {
			code: 'sq',
			label: 'Albanian',
		},
		iconFlagName: 'flag-albania',
		countryCode: '+355',
		isoCode: '008',
	},
	{
		label: 'Algeria',
		code: 'DZ',
		capital: 'Algiers',
		region: 'AF',
		currency: {
			code: 'DZD',
			label: 'Algerian dinar',
			symbol: 'د.ج',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: 'flag-algeria',
		countryCode: '+213',
		isoCode: '012',
	},
	{
		label: 'American Samoa',
		code: 'AS',
		capital: 'Pago Pago',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United State Dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '016',
	},
	{
		label: 'Andorra',
		code: 'AD',
		capital: 'Andorra la Vella',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'ca',
			label: 'Catalan',
		},
		iconFlagName: '',
		countryCode: '+376',
		isoCode: '020',
	},
	{
		label: 'Angola',
		code: 'AO',
		capital: 'Luanda',
		region: 'AF',
		currency: {
			code: 'AOA',
			label: 'Angolan kwanza',
			symbol: 'Kz',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: '',
		countryCode: '+244',
		isoCode: '024',
	},
	{
		label: 'Anguilla',
		code: 'AI',
		capital: 'The Valley',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+43',
		isoCode: '660',
	},
	{
		label: 'Antigua and Barbuda',
		code: 'AG',
		capital: "Saint John's",
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '028',
	},
	{
		label: 'Argentina',
		code: 'AR',
		capital: 'Buenos Aires',
		region: 'SA',
		currency: {
			code: 'ARS',
			label: 'Argentine peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-argentina',
		countryCode: '+54',
		isoCode: '032',
	},
	{
		label: 'Armenia',
		code: 'AM',
		capital: 'Yerevan',
		region: 'AS',
		currency: {
			code: 'AMD',
			label: 'Armenian dram',
			symbol: null,
		},
		language: {
			code: 'hy',
			label: 'Armenian',
		},
		iconFlagName: 'flag-armenia',
		countryCode: '+374',
		isoCode: '051',
	},
	{
		label: 'Aruba',
		code: 'AW',
		capital: 'Oranjestad',
		region: 'SA',
		currency: {
			code: 'AWG',
			label: 'Aruban florin',
			symbol: 'ƒ',
		},
		language: {
			code: 'nl',
			label: 'Dutch',
		},
		iconFlagName: 'flag-aruba',
		countryCode: '+297',
		isoCode: '533',
	},
	{
		label: 'Australia',
		code: 'AU',
		capital: 'Canberra',
		region: 'OC',
		currency: {
			code: 'AUD',
			label: 'Australian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-australia',
		countryCode: '+61',
		isoCode: '036',
	},
	{
		label: 'Austria',
		code: 'AT',
		capital: 'Vienna',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'de',
			label: 'German',
		},
		iconFlagName: 'flag-austria',
		countryCode: '+43',
		isoCode: '040',
	},
	{
		label: 'Azerbaijan',
		code: 'AZ',
		capital: 'Baku',
		region: 'AS',
		currency: {
			code: 'AZN',
			label: 'Azerbaijani manat',
			symbol: null,
		},
		language: {
			code: 'az',
			label: 'Azerbaijani',
		},
		iconFlagName: '',
		countryCode: '+994',
		isoCode: '031',
	},
	{
		label: 'Bahamas',
		code: 'BS',
		capital: 'Nassau',
		region: 'NA',
		currency: {
			code: 'BSD',
			label: 'Bahamian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-bahamas',
		countryCode: '+1',
		isoCode: '044',
	},
	{
		label: 'Bahrain',
		code: 'BH',
		capital: 'Manama',
		region: 'AS',
		currency: {
			code: 'BHD',
			label: 'Bahraini dinar',
			symbol: '.د.ب',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: 'flag-bahrain',
		countryCode: '+973',
		isoCode: '048',
	},
	{
		label: 'Bangladesh',
		code: 'BD',
		capital: 'Dhaka',
		region: 'AS',
		currency: {
			code: 'BDT',
			label: 'Bangladeshi taka',
			symbol: '৳',
		},
		language: {
			code: 'bn',
			label: 'Bengali',
		},
		iconFlagName: 'flag-bangladesh',
		countryCode: '+880',
		isoCode: '050',
	},
	{
		label: 'Barbados',
		code: 'BB',
		capital: 'Bridgetown',
		region: 'NA',
		currency: {
			code: 'BBD',
			label: 'Barbadian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '052',
	},
	{
		label: 'Belarus',
		code: 'BY',
		capital: 'Minsk',
		region: 'EU',
		currency: {
			code: 'BYN',
			label: 'New Belarusian ruble',
			symbol: 'Br',
		},
		language: {
			code: 'be',
			label: 'Belarusian',
		},
		iconFlagName: 'flag-belarus',
		countryCode: '+375',
		isoCode: '112',
	},
	{
		label: 'Belgium',
		code: 'BE',
		capital: 'Brussels',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'nl',
			label: 'Dutch',
		},
		iconFlagName: 'flag-belgium',
		countryCode: '+32',
		isoCode: '056',
	},
	{
		label: 'Belize',
		code: 'BZ',
		capital: 'Belmopan',
		region: 'NA',
		currency: {
			code: 'BZD',
			label: 'Belize dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+501',
		isoCode: '084',
	},
	{
		label: 'Benin',
		code: 'BJ',
		capital: 'Porto-Novo',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-benin',
		countryCode: '+229',
		isoCode: '204',
	},
	{
		label: 'Bermuda',
		code: 'BM',
		capital: 'Hamilton',
		region: 'NA',
		currency: {
			code: 'BMD',
			label: 'Bermudian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '060',
	},
	{
		label: 'Bhutan',
		code: 'BT',
		capital: 'Thimphu',
		region: 'AS',
		currency: {
			code: 'BTN',
			label: 'Bhutanese ngultrum',
			symbol: 'Nu.',
		},
		language: {
			code: 'dz',
			label: 'Dzongkha',
		},
		iconFlagName: '',
		countryCode: '+975',
		isoCode: '064',
	},
	{
		label: 'Bolivia (Plurinational State of)',
		code: 'BO',
		capital: 'Sucre',
		region: 'SA',
		currency: {
			code: 'BOB',
			label: 'Bolivian boliviano',
			symbol: 'Bs.',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-bolivia',
		countryCode: '+591',
		isoCode: '068',
	},
	{
		label: 'Bosnia and Herzegovina',
		code: 'BA',
		capital: 'Sarajevo',
		region: 'EU',
		currency: {
			code: 'BAM',
			label: 'Bosnia and Herzegovina convertible mark',
			symbol: null,
		},
		language: {
			code: 'bs',
			label: 'Bosnian',
		},
		iconFlagName: '',
		countryCode: '+387',
		isoCode: '070',
	},
	{
		label: 'Botswana',
		code: 'BW',
		capital: 'Gaborone',
		region: 'AF',
		currency: {
			code: 'BWP',
			label: 'Botswana pula',
			symbol: 'P',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-botswana',
		countryCode: '+267',
		isoCode: '072',
	},
	{
		label: 'Brazil',
		code: 'BR',
		capital: 'Brasília',
		region: 'SA',
		currency: {
			code: 'BRL',
			label: 'Brazilian real',
			symbol: 'R$',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: 'flag-brazil',
		countryCode: '+55',
		isoCode: '076',
	},
	{
		label: 'British Indian Ocean Territory',
		code: 'IO',
		capital: 'Diego Garcia',
		region: 'AF',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+246',
		isoCode: '086',
	},
	{
		label: 'Virgin Islands (British)',
		code: 'VG',
		capital: 'Road Town',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '092',
	},
	{
		label: 'Virgin Islands (U.S.)',
		code: 'VI',
		capital: 'Charlotte Amalie',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '850',
	},
	{
		label: 'Brunei Darussalam',
		code: 'BN',
		capital: 'Bandar Seri Begawan',
		region: 'AS',
		currency: {
			code: 'BND',
			label: 'Brunei dollar',
			symbol: '$',
		},
		language: {
			code: 'ms',
			label: 'Malay',
		},
		iconFlagName: '',
		countryCode: '+673',
		isoCode: '096',
	},
	{
		label: 'Bulgaria',
		code: 'BG',
		capital: 'Sofia',
		region: 'EU',
		currency: {
			code: 'BGN',
			label: 'Bulgarian lev',
			symbol: 'лв',
		},
		language: {
			code: 'bg',
			label: 'Bulgarian',
		},
		iconFlagName: 'flag-bulgaria',
		countryCode: '+359',
		isoCode: '100',
	},
	{
		label: 'Burkina Faso',
		code: 'BF',
		capital: 'Ouagadougou',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-burkina-faso',
		countryCode: '+226',
		isoCode: '854',
	},
	{
		label: 'Burundi',
		code: 'BI',
		capital: 'Bujumbura',
		region: 'AF',
		currency: {
			code: 'BIF',
			label: 'Burundian franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+257',
		isoCode: '108',
	},
	{
		label: 'Cambodia',
		code: 'KH',
		capital: 'Phnom Penh',
		region: 'AS',
		currency: {
			code: 'KHR',
			label: 'Cambodian riel',
			symbol: '៛',
		},
		language: {
			code: 'km',
			label: 'Khmer',
		},
		iconFlagName: 'flag-cambodia',
		countryCode: '+855',
		isoCode: '116',
	},
	{
		label: 'Cameroon',
		code: 'CM',
		capital: 'Yaoundé',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+237',
		isoCode: '120',
	},
	{
		label: 'Canada',
		code: 'CA',
		capital: 'Ottawa',
		region: 'NA',
		currency: {
			code: 'CAD',
			label: 'Canadian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-canada',
		countryCode: '+1',
		isoCode: '124',
	},
	{
		label: 'Cabo Verde',
		code: 'CV',
		capital: 'Praia',
		region: 'AF',
		currency: {
			code: 'CVE',
			label: 'Cape Verdean escudo',
			symbol: 'Esc',
		},
		language: {
			code: 'pt',
			iso639_2: 'por',
			label: 'Portuguese',
			nativeName: 'Português',
		},
		iconFlagName: '',
		countryCode: '+238',
		isoCode: '132',
	},
	{
		label: 'Cayman Islands',
		code: 'KY',
		capital: 'George Town',
		region: 'NA',
		demonym: 'Caymanian',
		currency: {
			code: 'KYD',
			label: 'Cayman Islands dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-cayman-islands',
		countryCode: '+1',
		isoCode: '136',
	},
	{
		label: 'Central African Republic',
		code: 'CF',
		capital: 'Bangui',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-central-african-republic',
		countryCode: '+236',
		isoCode: '140',
	},
	{
		label: 'Central African Republic',
		code: 'CF',
		capital: 'Bangui',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-central-african-republic',
		countryCode: '+236',
		isoCode: '140',
	},
	{
		label: 'Chile',
		code: 'CL',
		capital: 'Santiago',
		region: 'SA',
		currency: {
			code: 'CLP',
			label: 'Chilean peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			iso639_2: 'spa',
			label: 'Spanish',
			nativeName: 'Español',
		},
		iconFlagName: 'flag-chile',
		countryCode: '+56',
		isoCode: '152',
	},
	{
		label: 'China',
		code: 'CN',
		capital: 'Beijing',
		region: 'AS',
		currency: {
			code: 'CNY',
			label: 'Chinese yuan',
			symbol: '¥',
		},
		language: {
			code: 'zh',
			label: 'Chinese',
		},
		iconFlagName: 'flag-china',
		countryCode: '+86',
		isoCode: '156',
	},
	{
		label: 'Colombia',
		code: 'CO',
		capital: 'Bogotá',
		region: 'SA',
		currency: {
			code: 'COP',
			label: 'Colombian peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-colombia',
		countryCode: '+57',
		isoCode: '170',
	},
	{
		label: 'Comoros',
		code: 'KM',
		capital: 'Moroni',
		region: 'AF',
		currency: {
			code: 'KMF',
			label: 'Comorian franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+269',
		isoCode: '174',
	},
	{
		label: 'Congo',
		code: 'CG',
		capital: 'Brazzaville',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+242',
		isoCode: '178',
	},
	{
		label: 'Congo (Democratic Republic of the)',
		code: 'CD',
		capital: 'Kinshasa',
		region: 'AF',
		currency: {
			code: 'CDF',
			label: 'Congolese franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+243',
		isoCode: '180',
	},
	{
		label: 'Cook Islands',
		code: 'CK',
		capital: 'Avarua',
		region: 'OC',
		currency: {
			code: 'NZD',
			label: 'New Zealand dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+682',
		isoCode: '184',
	},
	{
		label: 'Costa Rica',
		code: 'CR',
		capital: 'San José',
		region: 'NA',
		currency: {
			code: 'CRC',
			label: 'Costa Rican colón',
			symbol: '₡',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-costa-rica',
		countryCode: '+506',
		isoCode: '188',
	},
	{
		label: 'Croatia',
		code: 'HR',
		capital: 'Zagreb',
		region: 'EU',
		currency: {
			code: 'HRK',
			label: 'Croatian kuna',
			symbol: 'kn',
		},
		language: {
			code: 'hr',
			label: 'Croatian',
		},
		iconFlagName: 'flag-croatia',
		countryCode: '+385',
		isoCode: '191',
	},
	{
		label: 'Cuba',
		code: 'CU',
		capital: 'Havana',
		region: 'NA',
		currency: {
			code: 'CUC',
			label: 'Cuban convertible peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: '',
		countryCode: '+53',
		isoCode: '192',
	},
	{
		label: 'Cuba',
		code: 'CU',
		capital: 'Havana',
		region: 'NA',
		currency: {
			code: 'CUC',
			label: 'Cuban convertible peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: '',
		countryCode: '+53',
		isoCode: '192',
	},
	{
		label: 'Cyprus',
		code: 'CY',
		capital: 'Nicosia',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'tr',
			label: 'Turkish',
		},
		iconFlagName: 'flag-cyprus',
		countryCode: '+357',
		isoCode: '196',
	},
	{
		label: 'Czech Republic',
		code: 'CZ',
		capital: 'Prague',
		region: 'EU',
		currency: {
			code: 'CZK',
			label: 'Czech koruna',
			symbol: 'Kč',
		},
		language: {
			code: 'cs',
			label: 'Czech',
		},
		iconFlagName: 'flag-czech-republic',
		countryCode: '+420',
		isoCode: '203',
	},
	{
		label: 'Denmark',
		code: 'DK',
		capital: 'Copenhagen',
		region: 'EU',
		currency: {
			code: 'DKK',
			label: 'Danish krone',
			symbol: 'kr',
		},
		language: {
			code: 'da',
			label: 'Danish',
		},
		iconFlagName: 'flag-denmark',
		countryCode: '+45',
		isoCode: '208',
	},
	{
		label: 'Djibouti',
		code: 'DJ',
		capital: 'Djibouti',
		region: 'AF',
		currency: {
			code: 'DJF',
			label: 'Djiboutian franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+253',
		isoCode: '262',
	},
	{
		label: 'Dominica',
		code: 'DM',
		capital: 'Roseau',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '212',
	},
	{
		label: 'Dominican Republic',
		code: 'DO',
		capital: 'Santo Domingo',
		region: 'NA',
		currency: {
			code: 'DOP',
			label: 'Dominican peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-dominican-republic',
		countryCode: '+1',
		isoCode: '214',
	},
	{
		label: 'Ecuador',
		code: 'EC',
		capital: 'Quito',
		region: 'SA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: '',
		countryCode: '+593',
		isoCode: '218',
	},
	{
		label: 'Egypt',
		code: 'EG',
		capital: 'Cairo',
		region: 'AF',
		currency: {
			code: 'EGP',
			label: 'Egyptian pound',
			symbol: '£',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: 'flag-egypt',
		countryCode: '+20',
		isoCode: '818',
	},
	{
		label: 'El Salvador',
		code: 'SV',
		capital: 'San Salvador',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-el-salvador',
		countryCode: '+503',
		isoCode: '222',
	},
	{
		label: 'Equatorial Guinea',
		code: 'GQ',
		capital: 'Malabo',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'es',
			iso639_2: 'spa',
			label: 'Spanish',
			nativeName: 'Español',
		},
		iconFlagName: '',
		countryCode: '+240',
		isoCode: '226',
	},
	{
		label: 'Eritrea',
		code: 'ER',
		capital: 'Asmara',
		region: 'AF',
		currency: {
			code: 'ERN',
			label: 'Eritrean nakfa',
			symbol: 'Nfk',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+291',
		isoCode: '232',
	},
	{
		label: 'Estonia',
		code: 'EE',
		capital: 'Tallinn',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'et',
			label: 'Estonian',
		},
		iconFlagName: 'flag-estonia',
		countryCode: '+372',
		isoCode: '233',
	},
	{
		label: 'Ethiopia',
		code: 'ET',
		capital: 'Addis Ababa',
		region: 'AF',
		currency: {
			code: 'ETB',
			label: 'Ethiopian birr',
			symbol: 'Br',
		},
		language: {
			code: 'am',
			label: 'Amharic',
		},
		iconFlagName: '',
		countryCode: '+251',
		isoCode: '231',
	},
	{
		label: 'Falkland Islands (Malvinas)',
		code: 'FK',
		capital: 'Stanley',
		region: 'SA',
		currency: {
			code: 'FKP',
			label: 'Falkland Islands pound',
			symbol: '£',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+500',
		isoCode: '238',
	},
	{
		label: 'Faroe Islands',
		code: 'FO',
		capital: 'Tórshavn',
		region: 'EU',
		currency: {
			code: 'DKK',
			label: 'Danish krone',
			symbol: 'kr',
		},
		language: {
			code: 'fo',
			label: 'Faroese',
		},
		iconFlagName: '',
		countryCode: '+298',
		isoCode: '234',
	},
	{
		label: 'Fiji',
		code: 'FJ',
		capital: 'Suva',
		region: 'OC',
		currency: {
			code: 'FJD',
			label: 'Fijian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+679',
		isoCode: '242',
	},
	{
		label: 'Finland',
		code: 'FI',
		capital: 'Helsinki',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fi',
			iso639_2: 'fin',
			label: 'Finnish',
			nativeName: 'suomi',
		},
		iconFlagName: 'flag-finland',
		countryCode: '+358',
		isoCode: '246',
	},
	{
		label: 'France',
		code: 'FR',
		capital: 'Paris',
		region: 'EU',
		demonym: 'French',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-france',
		countryCode: '+33',
		isoCode: '250',
	},
	{
		label: 'French Guiana',
		code: 'GF',
		capital: 'Cayenne',
		region: 'SA',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+594',
		isoCode: '254',
	},
	{
		label: 'French Polynesia',
		code: 'PF',
		capital: 'Papeetē',
		region: 'OC',
		currency: {
			code: 'XPF',
			label: 'CFP franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+689',
		isoCode: '258',
	},
	{
		label: 'Gabon',
		code: 'GA',
		capital: 'Libreville',
		region: 'AF',
		currency: {
			code: 'XAF',
			label: 'Central African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+241',
		isoCode: '266',
	},
	{
		label: 'Gambia',
		code: 'GM',
		capital: 'Banjul',
		region: 'AF',
		currency: {
			code: 'GMD',
			label: 'Gambian dalasi',
			symbol: 'D',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+220',
		isoCode: '270',
	},
	{
		label: 'Georgia',
		code: 'GE',
		capital: 'Tbilisi',
		region: 'AS',
		currency: {
			code: 'GEL',
			label: 'Georgian Lari',
			symbol: 'ლ',
		},
		language: {
			code: 'ka',
			label: 'Georgian',
		},
		iconFlagName: 'flag-georgia',
		countryCode: '+995',
		isoCode: '268',
	},
	{
		label: 'Germany',
		code: 'DE',
		capital: 'Berlin',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'de',
			label: 'German',
		},
		iconFlagName: 'flag-germany',
		countryCode: '+49',
		isoCode: '276',
	},
	{
		label: 'Ghana',
		code: 'GH',
		capital: 'Accra',
		region: 'AF',
		currency: {
			code: 'GHS',
			label: 'Ghanaian cedi',
			symbol: '₵',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-ghana',
		countryCode: '+233',
		isoCode: '288',
	},
	{
		label: 'Gibraltar',
		code: 'GI',
		capital: 'Gibraltar',
		region: 'EU',
		currency: {
			code: 'GIP',
			label: 'Gibraltar pound',
			symbol: '£',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+350',
		isoCode: '292',
	},
	{
		label: 'Greece',
		code: 'GR',
		capital: 'Athens',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'el',
			label: 'Greek (modern)',
		},
		iconFlagName: 'flag-greece',
		countryCode: '+30',
		isoCode: '300',
	},
	{
		label: 'Greenland',
		code: 'GL',
		capital: 'Nuuk',
		region: 'NA',
		currency: {
			code: 'DKK',
			label: 'Danish krone',
			symbol: 'kr',
		},
		language: {
			code: 'kl',
			label: 'Kalaallisut',
		},
		iconFlagName: '',
		countryCode: '+299',
		isoCode: '304',
	},
	{
		label: 'Grenada',
		code: 'GD',
		capital: "St. George's",
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-grenada',
		countryCode: '+1',
		isoCode: '308',
	},
	{
		label: 'Guadeloupe',
		code: 'GP',
		capital: 'Basse-Terre',
		region: 'NA',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+590',
		isoCode: '312',
	},
	{
		label: 'Guam',
		code: 'GU',
		capital: 'Hagåtña',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '316',
	},
	{
		label: 'Guatemala',
		code: 'GT',
		capital: 'Guatemala City',
		region: 'NA',
		currency: {
			code: 'GTQ',
			label: 'Guatemalan quetzal',
			symbol: 'Q',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-guatemala',
		countryCode: '+502',
		isoCode: '320',
	},
	{
		label: 'Guinea',
		code: 'GN',
		capital: 'Conakry',
		region: 'AF',
		currency: {
			code: 'GNF',
			label: 'Guinean franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+224',
		isoCode: '324',
	},
	{
		label: 'Guinea-Bissau',
		code: 'GW',
		capital: 'Bissau',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: '',
		countryCode: '+245',
		isoCode: '624',
	},
	{
		label: 'Guyana',
		code: 'GY',
		capital: 'Georgetown',
		region: 'SA',
		currency: {
			code: 'GYD',
			label: 'Guyanese dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+592',
		isoCode: '328',
	},
	{
		label: 'Haiti',
		code: 'HT',
		capital: 'Port-au-Prince',
		region: 'Americas',
		currency: {
			code: 'HTG',
			label: 'Haitian gourde',
			symbol: 'G',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+509',
		isoCode: '332',
	},
	{
		label: 'Holy See',
		code: 'VA',
		capital: 'Rome',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+39',
		isoCode: '336',
	},
	{
		label: 'Honduras',
		code: 'HN',
		capital: 'Tegucigalpa',
		region: 'NA',
		currency: {
			code: 'HNL',
			label: 'Honduran lempira',
			symbol: 'L',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-honduras',
		countryCode: '+504',
		isoCode: '340',
	},
	{
		label: 'Hong Kong',
		code: 'HK',
		capital: 'City of Victoria',
		region: 'AS',
		currency: {
			code: 'HKD',
			label: 'Hong Kong dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-hong-kong',
		countryCode: '+852',
		isoCode: '344',
	},
	{
		label: 'Hungary',
		code: 'HU',
		capital: 'Budapest',
		region: 'EU',
		currency: {
			code: 'HUF',
			label: 'Hungarian forint',
			symbol: 'Ft',
		},
		language: {
			code: 'hu',
			label: 'Hungarian',
		},
		iconFlagName: 'flag-hungary',
		countryCode: '+36',
		isoCode: '348',
	},
	{
		label: 'Iceland',
		code: 'IS',
		capital: 'Reykjavík',
		region: 'EU',
		currency: {
			code: 'ISK',
			label: 'Icelandic króna',
			symbol: 'kr',
		},
		language: {
			code: 'is',
			label: 'Icelandic',
		},
		iconFlagName: 'flag-iceland',
		countryCode: '+354',
		isoCode: '352',
	},
	{
		label: 'India',
		code: 'IN',
		capital: 'New Delhi',
		region: 'AS',
		currency: {
			code: 'INR',
			label: 'Indian rupee',
			symbol: '₹',
		},
		language: {
			code: 'hi',
			label: 'Hindi',
		},
		iconFlagName: 'flag-india',
		countryCode: '+91',
		isoCode: '356',
	},
	{
		label: 'Indonesia',
		code: 'ID',
		capital: 'Jakarta',
		region: 'AS',
		currency: {
			code: 'IDR',
			label: 'Indonesian rupiah',
			symbol: 'Rp',
		},
		language: {
			code: 'id',
			label: 'Indonesian',
		},
		iconFlagName: 'flag-indonesia',
		countryCode: '+62',
		isoCode: '360',
	},
	{
		label: "Côte d'Ivoire",
		code: 'CI',
		capital: 'Yamoussoukro',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+225',
		isoCode: '384',
	},
	{
		label: 'Iran (Islamic Republic of)',
		code: 'IR',
		capital: 'Tehran',
		region: 'AS',
		currency: {
			code: 'IRR',
			label: 'Iranian rial',
			symbol: '﷼',
		},
		language: {
			code: 'fa',
			label: 'Persian (Farsi)',
		},
		iconFlagName: '',
		countryCode: '+98',
		isoCode: '364',
	},
	{
		label: 'Iraq',
		code: 'IQ',
		capital: 'Baghdad',
		region: 'AS',
		currency: {
			code: 'IQD',
			label: 'Iraqi dinar',
			symbol: 'ع.د',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+964',
		isoCode: '368',
	},
	{
		label: 'Ireland',
		code: 'IE',
		capital: 'Dublin',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'ga',
			label: 'Irish',
		},
		iconFlagName: 'flag-ireland',
		countryCode: '+353',
		isoCode: '372',
	},
	{
		label: 'Israel',
		code: 'IL',
		capital: 'Jerusalem',
		region: 'AS',
		currency: {
			code: 'ILS',
			label: 'Israeli new shekel',
			symbol: '₪',
		},
		language: {
			code: 'he',
			label: 'Hebrew (modern)',
		},
		iconFlagName: 'flag-israel',
		countryCode: '+972',
		isoCode: '376',
	},
	{
		label: 'Italy',
		code: 'IT',
		capital: 'Rome',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'it',
			label: 'Italian',
		},
		iconFlagName: 'flag-italy',
		countryCode: '+39',
		isoCode: '380',
	},
	{
		label: 'Jamaica',
		code: 'JM',
		capital: 'Kingston',
		region: 'NA',
		currency: {
			code: 'JMD',
			label: 'Jamaican dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-jamaica',
		countryCode: '+1',
		isoCode: '388',
	},
	{
		label: 'Japan',
		code: 'JP',
		capital: 'Tokyo',
		region: 'AS',
		currency: {
			code: 'JPY',
			label: 'Japanese yen',
			symbol: '¥',
		},
		language: {
			code: 'ja',
			label: 'Japanese',
		},
		iconFlagName: 'flag-japan',
		countryCode: '+81',
		isoCode: '392',
	},
	{
		label: 'Jordan',
		code: 'JO',
		capital: 'Amman',
		region: 'AS',
		currency: {
			code: 'JOD',
			label: 'Jordanian dinar',
			symbol: 'د.ا',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+962',
		isoCode: '400',
	},
	{
		label: 'Kazakhstan',
		code: 'KZ',
		capital: 'Astana',
		region: 'AS',
		currency: {
			code: 'KZT',
			label: 'Kazakhstani tenge',
			symbol: null,
		},
		language: {
			code: 'kk',
			label: 'Kazakh',
		},
		iconFlagName: '',
		countryCode: '+7',
		isoCode: '398',
	},
	{
		label: 'Kenya',
		code: 'KE',
		capital: 'Nairobi',
		region: 'AF',
		currency: {
			code: 'KES',
			label: 'Kenyan shilling',
			symbol: 'Sh',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+254',
		isoCode: '404',
	},
	{
		label: 'Kiribati',
		code: 'KI',
		capital: 'South Tarawa',
		region: 'OC',
		currency: {
			code: 'AUD',
			label: 'Australian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+686',
		isoCode: '296',
	},
	{
		label: 'Kuwait',
		code: 'KW',
		capital: 'Kuwait City',
		region: 'AS',
		currency: {
			code: 'KWD',
			label: 'Kuwaiti dinar',
			symbol: 'د.ك',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+965',
		isoCode: '414',
	},
	{
		label: 'Kyrgyzstan',
		code: 'KG',
		capital: 'Bishkek',
		region: 'AS',
		currency: {
			code: 'KGS',
			label: 'Kyrgyzstani som',
			symbol: 'с',
		},
		language: {
			code: 'ky',
			label: 'Kyrgyz',
		},
		iconFlagName: '',
		countryCode: '+996',
		isoCode: '417',
	},
	{
		label: "Lao People's Democratic Republic",
		code: 'LA',
		capital: 'Vientiane',
		region: 'AS',
		currency: {
			code: 'LAK',
			label: 'Lao kip',
			symbol: '₭',
		},
		language: {
			code: 'lo',
			label: 'Lao',
		},
		iconFlagName: '',
		countryCode: '+856',
		isoCode: '418',
	},
	{
		label: 'Latvia',
		code: 'LV',
		capital: 'Riga',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'lv',
			label: 'Latvian',
		},
		iconFlagName: 'flag-latvia',
		countryCode: '+371',
		isoCode: '428',
	},
	{
		label: 'Lebanon',
		code: 'LB',
		capital: 'Beirut',
		region: 'AS',
		currency: {
			code: 'LBP',
			label: 'Lebanese pound',
			symbol: 'ل.ل',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+961',
		isoCode: '422',
	},
	{
		label: 'Lesotho',
		code: 'LS',
		capital: 'Maseru',
		region: 'AF',
		currency: {
			code: 'LSL',
			label: 'Lesotho loti',
			symbol: 'L',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+266',
		isoCode: '426',
	},
	{
		label: 'Liberia',
		code: 'LR',
		capital: 'Monrovia',
		region: 'AF',
		currency: {
			code: 'LRD',
			label: 'Liberian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+231',
		isoCode: '430',
	},
	{
		label: 'Libya',
		code: 'LY',
		capital: 'Tripoli',
		region: 'AF',
		currency: {
			code: 'LYD',
			label: 'Libyan dinar',
			symbol: 'ل.د',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+218',
		isoCode: '434',
	},
	{
		label: 'Liechtenstein',
		code: 'LI',
		capital: 'Vaduz',
		region: 'EU',
		currency: {
			code: 'CHF',
			label: 'Swiss franc',
			symbol: 'Fr',
		},
		language: {
			code: 'de',
			label: 'German',
		},
		iconFlagName: 'flag-liechtenstein',
		countryCode: '+423',
		isoCode: '438',
	},
	{
		label: 'Lithuania',
		code: 'LT',
		capital: 'Vilnius',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'lt',
			label: 'Lithuanian',
		},
		iconFlagName: 'flag-lithuania',
		countryCode: '+370',
		isoCode: '440',
	},
	{
		label: 'Luxembourg',
		code: 'LU',
		capital: 'Luxembourg',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: 'flag-luxembourg',
		countryCode: '+352',
		isoCode: '442',
	},
	{
		label: 'Macao',
		code: 'MO',
		capital: '',
		region: 'AS',
		currency: {
			code: 'MOP',
			label: 'Macanese pataca',
			symbol: 'P',
		},
		language: {
			code: 'zh',
			label: 'Chinese',
		},
		iconFlagName: 'flag-macao',
		countryCode: '+853',
		isoCode: '446',
	},
	{
		label: 'Macedonia (the former Yugoslav Republic of)',
		code: 'MK',
		capital: 'Skopje',
		region: 'EU',
		currency: {
			code: 'MKD',
			label: 'Macedonian denar',
			symbol: 'ден',
		},
		language: {
			code: 'mk',
			label: 'Macedonian',
		},
		iconFlagName: '',
		countryCode: '+389',
		isoCode: '807',
	},
	{
		label: 'Madagascar',
		code: 'MG',
		capital: 'Antananarivo',
		region: 'AF',
		currency: {
			code: 'MGA',
			label: 'Malagasy ariary',
			symbol: 'Ar',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+261',
		isoCode: '450',
	},
	{
		label: 'Malawi',
		code: 'MW',
		capital: 'Lilongwe',
		region: 'AF',
		currency: {
			code: 'MWK',
			label: 'Malawian kwacha',
			symbol: 'MK',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+265',
		isoCode: '454',
	},
	{
		label: 'Malaysia',
		code: 'MY',
		capital: 'Kuala Lumpur',
		region: 'AS',
		currency: {
			code: 'MYR',
			label: 'Malaysian ringgit',
			symbol: 'RM',
		},
		language: {
			code: null,
			label: 'Malaysian',
		},
		iconFlagName: 'flag-malaysia',
		countryCode: '+60',
		isoCode: '458',
	},
	{
		label: 'Maldives',
		code: 'MV',
		capital: 'Malé',
		region: 'AS',
		currency: {
			code: 'MVR',
			label: 'Maldivian rufiyaa',
			symbol: '.ރ',
		},
		language: {
			code: 'dv',
			label: 'Divehi',
		},
		iconFlagName: '',
		countryCode: '+960',
		isoCode: '462',
	},
	{
		label: 'Mali',
		code: 'ML',
		capital: 'Bamako',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+223',
		isoCode: '466',
	},
	{
		label: 'Malta',
		code: 'MT',
		capital: 'Valletta',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'mt',
			label: 'Maltese',
		},
		iconFlagName: 'flag-malta',
		countryCode: '+356',
		isoCode: '470',
	},
	{
		label: 'Marshall Islands',
		code: 'MH',
		capital: 'Majuro',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+692',
		isoCode: '584',
	},
	{
		label: 'Martinique',
		code: 'MQ',
		capital: 'Fort-de-France',
		region: 'Americas',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+596',
		isoCode: '474',
	},
	{
		label: 'Mauritania',
		code: 'MR',
		capital: 'Nouakchott',
		region: 'AF',
		currency: {
			code: 'MRO',
			label: 'Mauritanian ouguiya',
			symbol: 'UM',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+222',
		isoCode: '478',
	},
	{
		label: 'Mauritius',
		code: 'MU',
		capital: 'Port Louis',
		region: 'AF',
		currency: {
			code: 'MUR',
			label: 'Mauritian rupee',
			symbol: '₨',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-mauritius',
		countryCode: '+230',
		isoCode: '480',
	},
	{
		label: 'Mayotte',
		code: 'YT',
		capital: 'Mamoudzou',
		region: 'AF',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+262',
		isoCode: '175',
	},
	{
		label: 'Mexico',
		code: 'MX',
		capital: 'Mexico City',
		region: 'NA',
		currency: {
			code: 'MXN',
			label: 'Mexican peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-mexico',
		countryCode: '+52',
		isoCode: '484',
	},
	{
		label: 'Micronesia (Federated States of)',
		code: 'FM',
		capital: 'Palikir',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+691',
		isoCode: '583',
	},
	{
		label: 'Moldova (Republic of)',
		code: 'MD',
		capital: 'Chișinău',
		region: 'EU',
		currency: {
			code: 'MDL',
			label: 'Moldovan leu',
			symbol: 'L',
		},
		language: {
			code: 'ro',
			label: 'Romanian',
		},
		iconFlagName: 'flag-moldova',
		countryCode: '+373',
		isoCode: '498',
	},
	{
		label: 'Monaco',
		code: 'MC',
		capital: 'Monaco',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+377',
		isoCode: '492',
	},
	{
		label: 'Mongolia',
		code: 'MN',
		capital: 'Ulan Bator',
		region: 'AS',
		currency: {
			code: 'MNT',
			label: 'Mongolian tögrög',
			symbol: '₮',
		},
		language: {
			code: 'mn',
			label: 'Mongolian',
		},
		iconFlagName: '',
		countryCode: '+976',
		isoCode: '496',
	},
	{
		label: 'Montenegro',
		code: 'ME',
		capital: 'Podgorica',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'sr',
			label: 'Serbian',
		},
		iconFlagName: '',
		countryCode: '+382',
		isoCode: '499',
	},
	{
		label: 'Montserrat',
		code: 'MS',
		capital: 'Plymouth',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '500',
	},
	{
		label: 'Morocco',
		code: 'MA',
		capital: 'Rabat',
		region: 'AF',
		currency: {
			code: 'MAD',
			label: 'Moroccan dirham',
			symbol: 'د.م.',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+212',
		isoCode: '504',
	},
	{
		label: 'Mozambique',
		code: 'MZ',
		capital: 'Maputo',
		region: 'AF',
		currency: {
			code: 'MZN',
			label: 'Mozambican metical',
			symbol: 'MT',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: '',
		countryCode: '+258',
		isoCode: '508',
	},
	{
		label: 'Myanmar',
		code: 'MM',
		capital: 'Naypyidaw',
		region: 'AS',
		currency: {
			code: 'MMK',
			label: 'Burmese kyat',
			symbol: 'Ks',
		},
		language: {
			code: 'my',
			label: 'Burmese',
		},
		iconFlagName: '',
		countryCode: '+95',
		isoCode: '104',
	},
	{
		label: 'Namibia',
		code: 'NA',
		capital: 'Windhoek',
		region: 'AF',
		currency: {
			code: 'NAD',
			label: 'Namibian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+264',
		isoCode: '516',
	},
	{
		label: 'Nauru',
		code: 'NR',
		capital: 'Yaren',
		region: 'OC',
		currency: {
			code: 'AUD',
			label: 'Australian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+674',
		isoCode: '520',
	},
	{
		label: 'Nepal',
		code: 'NP',
		capital: 'Kathmandu',
		region: 'AS',
		currency: {
			code: 'NPR',
			label: 'Nepalese rupee',
			symbol: '₨',
		},
		language: {
			code: 'ne',
			label: 'Nepali',
		},
		iconFlagName: '',
		countryCode: '+977',
		isoCode: '524',
	},
	{
		label: 'Netherlands',
		code: 'NL',
		capital: 'Amsterdam',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'nl',
			label: 'Dutch',
		},
		iconFlagName: 'flag-netherlands',
		countryCode: '+31',
		isoCode: '528',
	},
	{
		label: 'New Caledonia',
		code: 'NC',
		capital: 'Nouméa',
		region: 'OC',
		currency: {
			code: 'XPF',
			label: 'CFP franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+687',
		isoCode: '540',
	},
	{
		label: 'New Zealand',
		code: 'NZ',
		capital: 'Wellington',
		region: 'OC',
		currency: {
			code: 'NZD',
			label: 'New Zealand dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-new-zealand',
		countryCode: '+64',
		isoCode: '554',
	},
	{
		label: 'Nicaragua',
		code: 'NI',
		capital: 'Managua',
		region: 'NA',
		currency: {
			code: 'NIO',
			label: 'Nicaraguan córdoba',
			symbol: 'C$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: '',
		countryCode: '+505',
		isoCode: '558',
	},
	{
		label: 'Niger',
		code: 'NE',
		capital: 'Niamey',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+227',
		isoCode: '562',
	},
	{
		label: 'Nigeria',
		code: 'NG',
		capital: 'Abuja',
		region: 'AF',
		currency: {
			code: 'NGN',
			label: 'Nigerian naira',
			symbol: '₦',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-nigeria',
		countryCode: '+234',
		isoCode: '566',
	},
	{
		label: 'Niue',
		code: 'NU',
		capital: 'Alofi',
		region: 'OC',
		currency: {
			code: 'NZD',
			label: 'New Zealand dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+683',
		isoCode: '570',
	},
	{
		label: 'Norfolk Island',
		code: 'NF',
		capital: 'Kingston',
		region: 'OC',
		currency: {
			code: 'AUD',
			label: 'Australian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+672',
		isoCode: '574',
	},
	{
		label: "Korea (Democratic People's Republic of)",
		code: 'KP',
		capital: 'Pyongyang',
		region: 'AS',
		currency: {
			code: 'KPW',
			label: 'North Korean won',
			symbol: '₩',
		},
		language: {
			code: 'ko',
			label: 'Korean',
		},
		iconFlagName: '',
		countryCode: '+850',
		isoCode: '408',
	},
	{
		label: 'Northern Mariana Islands',
		code: 'MP',
		capital: 'Saipan',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '580',
	},
	{
		label: 'Norway',
		code: 'NO',
		capital: 'Oslo',
		region: 'EU',
		currency: {
			code: 'NOK',
			label: 'Norwegian krone',
			symbol: 'kr',
		},
		language: {
			code: 'no',
			label: 'Norwegian',
		},
		iconFlagName: 'flag-norway',
		countryCode: '+47',
		isoCode: '578',
	},
	{
		label: 'Oman',
		code: 'OM',
		capital: 'Muscat',
		region: 'AS',
		currency: {
			code: 'OMR',
			label: 'Omani rial',
			symbol: 'ر.ع.',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+968',
		isoCode: '512',
	},
	{
		label: 'Pakistan',
		code: 'PK',
		capital: 'Islamabad',
		region: 'AS',
		currency: {
			code: 'PKR',
			label: 'Pakistani rupee',
			symbol: '₨',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-pakistan',
		countryCode: '+92',
		isoCode: '586',
	},
	{
		label: 'Palau',
		code: 'PW',
		capital: 'Ngerulmud',
		region: 'OC',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+680',
		isoCode: '585',
	},
	{
		label: 'Palestine',
		code: 'PS',
		capital: 'Ramallah',
		region: 'AS',
		currency: {
			code: 'ILS',
			label: 'Israeli new sheqel',
			symbol: '₪',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+970',
		isoCode: '275',
	},
	{
		label: 'Panama',
		code: 'PA',
		capital: 'Panama City',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-panama',
		countryCode: '+507',
		isoCode: '591',
	},
	{
		label: 'Papua New Guinea',
		code: 'PG',
		capital: 'Port Moresby',
		region: 'OC',
		currency: {
			code: 'PGK',
			label: 'Papua New Guinean kina',
			symbol: 'K',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+675',
		isoCode: '598',
	},
	{
		label: 'Paraguay',
		code: 'PY',
		capital: 'Asunción',
		region: 'SA',
		currency: {
			code: 'PYG',
			label: 'Paraguayan guaraní',
			symbol: '₲',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: '',
		countryCode: '+595',
		isoCode: '600',
	},
	{
		label: 'Peru',
		code: 'PE',
		capital: 'Lima',
		region: 'SA',
		currency: {
			code: 'PEN',
			label: 'Peruvian sol',
			symbol: 'S/.',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-peru',
		countryCode: '+51',
		isoCode: '604',
	},
	{
		label: 'Philippines',
		code: 'PH',
		capital: 'Manila',
		region: 'AS',
		currency: {
			code: 'PHP',
			label: 'Philippine peso',
			symbol: '₱',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-philippines',
		countryCode: '+63',
		isoCode: '608',
	},
	{
		label: 'Poland',
		code: 'PL',
		capital: 'Warsaw',
		region: 'EU',
		currency: {
			code: 'PLN',
			label: 'Polish złoty',
			symbol: 'zł',
		},
		language: {
			code: 'pl',
			label: 'Polish',
		},
		iconFlagName: 'flag-poland',
		countryCode: '+48',
		isoCode: '616',
	},
	{
		label: 'Portugal',
		code: 'PT',
		capital: 'Lisbon',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: 'flag-portugal',
		countryCode: '+351',
		isoCode: '620',
	},
	{
		label: 'Puerto Rico',
		code: 'PR',
		capital: 'San Juan',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-puertorico',
		countryCode: '+1',
		isoCode: '630',
	},
	{
		label: 'Qatar',
		code: 'QA',
		capital: 'Doha',
		region: 'AS',
		currency: {
			code: 'QAR',
			label: 'Qatari riyal',
			symbol: 'ر.ق',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+974',
		isoCode: '634',
	},
	{
		label: 'Republic of Kosovo',
		code: 'XK',
		capital: 'Pristina',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'sq',
			label: 'Albanian',
		},
		iconFlagName: '',
		countryCode: '+381',
		isoCode: '383',
	},
	{
		label: 'Réunion',
		code: 'RE',
		capital: 'Saint-Denis',
		region: 'AF',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+262',
		isoCode: '638',
	},
	{
		label: 'Romania',
		code: 'RO',
		capital: 'Bucharest',
		region: 'EU',
		currency: {
			code: 'RON',
			label: 'Romanian leu',
			symbol: 'lei',
		},
		language: {
			code: 'ro',
			label: 'Romanian',
		},
		iconFlagName: 'flag-romania',
		countryCode: '+40',
		isoCode: '642',
	},
	{
		label: 'Russian Federation',
		code: 'RU',
		capital: 'Moscow',
		region: 'EU',
		currency: {
			code: 'RUB',
			label: 'Russian ruble',
			symbol: '₽',
		},
		language: {
			code: 'ru',
			label: 'Russian',
		},
		iconFlagName: 'flag-russia',
		countryCode: '+7',
		isoCode: '643',
	},
	{
		label: 'Rwanda',
		code: 'RW',
		capital: 'Kigali',
		region: 'AF',
		currency: {
			code: 'RWF',
			label: 'Rwandan franc',
			symbol: 'Fr',
		},
		language: {
			code: 'rw',
			label: 'Kinyarwanda',
		},
		iconFlagName: 'flag-rwanda',
		countryCode: '+250',
		isoCode: '646',
	},
	{
		label: 'Saint Barthélemy',
		code: 'BL',
		capital: 'Gustavia',
		region: 'NA',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+590',
		isoCode: '652',
	},
	{
		label: 'Saint Helena, Ascension and Tristan da Cunha',
		code: 'SH',
		capital: 'Jamestown',
		region: 'AF',
		currency: {
			code: 'SHP',
			label: 'Saint Helena pound',
			symbol: '£',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+290',
		isoCode: '654',
	},
	{
		label: 'Saint Kitts and Nevis',
		code: 'KN',
		capital: 'Basseterre',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '659',
	},
	{
		label: 'Saint Lucia',
		code: 'LC',
		capital: 'Castries',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '662',
	},
	{
		label: 'Saint Martin (French part)',
		code: 'MF',
		capital: 'Marigot',
		region: 'NA',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+590',
		isoCode: '663',
	},
	{
		label: 'Saint Pierre and Miquelon',
		code: 'PM',
		capital: 'Saint-Pierre',
		region: 'NA',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+508',
		isoCode: '666',
	},
	{
		label: 'Saint Vincent and the Grenadines',
		code: 'VC',
		capital: 'Kingstown',
		region: 'NA',
		currency: {
			code: 'XCD',
			label: 'East Caribbean dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '670',
	},
	{
		label: 'Samoa',
		code: 'WS',
		capital: 'Apia',
		region: 'OC',
		currency: {
			code: 'WST',
			label: 'Samoan tālā',
			symbol: 'T',
		},
		language: {
			code: 'sm',
			label: 'Samoan',
		},
		iconFlagName: '',
		countryCode: '+685',
		isoCode: '882',
	},
	{
		label: 'San Marino',
		code: 'SM',
		capital: 'City of San Marino',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'it',
			label: 'Italian',
		},
		iconFlagName: '',
		countryCode: '+378',
		isoCode: '674',
	},
	{
		label: 'Sao Tome and Principe',
		code: 'ST',
		capital: 'São Tomé',
		region: 'AF',
		currency: {
			code: 'STD',
			label: 'São Tomé and Príncipe dobra',
			symbol: 'Db',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: '',
		countryCode: '+239',
		isoCode: '678',
	},
	{
		label: 'Saudi Arabia',
		code: 'SA',
		capital: 'Riyadh',
		region: 'AS',
		currency: {
			code: 'SAR',
			label: 'Saudi riyal',
			symbol: 'ر.س',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: 'flag-saudi-arabia',
		countryCode: '+966',
		isoCode: '682',
	},
	{
		label: 'Senegal',
		code: 'SN',
		capital: 'Dakar',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+221',
		isoCode: '686',
	},
	{
		label: 'Serbia',
		code: 'RS',
		capital: 'Belgrade',
		region: 'EU',
		currency: {
			code: 'RSD',
			label: 'Serbian dinar',
			symbol: 'дин.',
		},
		language: {
			code: 'sr',
			label: 'Serbian',
		},
		iconFlagName: 'flag-serbia',
		countryCode: '+381',
		isoCode: '688',
	},
	{
		label: 'Seychelles',
		code: 'SC',
		capital: 'Victoria',
		region: 'AF',
		currency: {
			code: 'SCR',
			label: 'Seychellois rupee',
			symbol: '₨',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+248',
		isoCode: '690',
	},
	{
		label: 'Sierra Leone',
		code: 'SL',
		capital: 'Freetown',
		region: 'AF',
		currency: {
			code: 'SLL',
			label: 'Sierra Leonean leone',
			symbol: 'Le',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+232',
		isoCode: '694',
	},
	{
		label: 'Singapore',
		code: 'SG',
		capital: 'Singapore',
		region: 'AS',
		currency: {
			code: 'SGD',
			label: 'Singapore dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-singapore',
		countryCode: '+65',
		isoCode: '702',
	},
	{
		label: 'Singapore',
		code: 'SG',
		capital: 'Singapore',
		region: 'AS',
		currency: {
			code: 'SGD',
			label: 'Singapore dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-singapore',
		countryCode: '+65',
		isoCode: '702',
	},
	{
		label: 'Slovakia',
		code: 'SK',
		capital: 'Bratislava',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'sk',
			label: 'Slovak',
		},
		iconFlagName: 'flag-slovakia',
		countryCode: '+421',
		isoCode: '703',
	},
	{
		label: 'Slovenia',
		code: 'SI',
		capital: 'Ljubljana',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'sl',
			label: 'Slovene',
		},
		iconFlagName: 'flag-slovenia',
		countryCode: '+386',
		isoCode: '705',
	},
	{
		label: 'Solomon Islands',
		code: 'SB',
		capital: 'Honiara',
		region: 'OC',
		currency: {
			code: 'SBD',
			label: 'Solomon Islands dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+677',
		isoCode: '090',
	},
	{
		label: 'Somalia',
		code: 'SO',
		capital: 'Mogadishu',
		region: 'AF',
		currency: {
			code: 'SOS',
			label: 'Somali shilling',
			symbol: 'Sh',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+252',
		isoCode: '706',
	},
	{
		label: 'South Africa',
		code: 'ZA',
		capital: 'Pretoria',
		region: 'AF',
		currency: {
			code: 'ZAR',
			label: 'South African rand',
			symbol: 'R',
		},
		language: {
			code: 'en',
			iso639_2: 'eng',
			label: 'English',
			nativeName: 'English',
		},
		iconFlagName: 'flag-south-africa',
		countryCode: '+27',
		isoCode: '710',
	},
	{
		label: 'Korea (Republic of)',
		code: 'KR',
		capital: 'Seoul',
		region: 'AS',
		currency: {
			code: 'KRW',
			label: 'South Korean won',
			symbol: '₩',
		},
		language: {
			code: 'ko',
			label: 'Korean',
		},
		iconFlagName: 'flag-south-korea',
		countryCode: '+82',
		isoCode: '410',
	},
	{
		label: 'Spain',
		code: 'ES',
		capital: 'Madrid',
		region: 'EU',
		currency: {
			code: 'EUR',
			label: 'Euro',
			symbol: '€',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-spain',
		countryCode: '+34',
		isoCode: '724',
	},
	{
		label: 'Sri Lanka',
		code: 'LK',
		capital: 'Colombo',
		region: 'AS',
		currency: {
			code: 'LKR',
			label: 'Sri Lankan rupee',
			symbol: 'Rs',
		},
		language: {
			code: 'si',
			iso639_2: 'sin',
			label: 'Sinhalese',
			nativeName: 'සිංහල',
		},
		iconFlagName: 'flag-sri-lanka',
		countryCode: '+94',
		isoCode: '144',
	},
	{
		label: 'Sudan',
		code: 'SD',
		capital: 'Khartoum',
		region: 'AF',
		currency: {
			code: 'SDG',
			label: 'Sudanese pound',
			symbol: 'ج.س.',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+249',
		isoCode: '729',
	},
	{
		label: 'Suriname',
		code: 'SR',
		capital: 'Paramaribo',
		region: 'SA',
		currency: {
			code: 'SRD',
			label: 'Surinamese dollar',
			symbol: '$',
		},
		language: {
			code: 'nl',
			label: 'Dutch',
		},
		iconFlagName: '',
		countryCode: '+597',
		isoCode: '740',
	},
	{
		label: 'Swaziland',
		code: 'SZ',
		capital: 'Lobamba',
		region: 'AF',
		currency: {
			code: 'SZL',
			label: 'Swazi lilangeni',
			symbol: 'L',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+268',
		isoCode: '748',
	},
	{
		label: 'Sweden',
		code: 'SE',
		capital: 'Stockholm',
		region: 'EU',
		currency: {
			code: 'SEK',
			label: 'Swedish krona',
			symbol: 'kr',
		},
		language: {
			code: 'sv',
			label: 'Swedish',
		},
		iconFlagName: 'flag-sweden',
		countryCode: '+46',
		isoCode: '752',
	},
	{
		label: 'Switzerland',
		code: 'CH',
		capital: 'Bern',
		region: 'EU',
		currency: {
			code: 'CHF',
			label: 'Swiss franc',
			symbol: 'Fr',
		},
		language: {
			code: 'de',
			label: 'German',
		},
		iconFlagName: 'flag-switzerland',
		countryCode: '+41',
		isoCode: '756',
	},
	{
		label: 'Syrian Arab Republic',
		code: 'SY',
		capital: 'Damascus',
		region: 'AS',
		currency: {
			code: 'SYP',
			label: 'Syrian pound',
			symbol: '£',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+963',
		isoCode: '760',
	},
	{
		label: 'Taiwan',
		code: 'TW',
		capital: 'Taipei',
		region: 'AS',
		currency: {
			code: 'TWD',
			label: 'New Taiwan dollar',
			symbol: '$',
		},
		language: {
			code: 'zh',
			label: 'Chinese',
		},
		iconFlagName: 'flag-taiwan',
		countryCode: '+886',
		isoCode: '158',
	},
	{
		label: 'Tajikistan',
		code: 'TJ',
		capital: 'Dushanbe',
		region: 'AS',
		currency: {
			code: 'TJS',
			label: 'Tajikistani somoni',
			symbol: 'ЅМ',
		},
		language: {
			code: 'tg',
			label: 'Tajik',
		},
		iconFlagName: 'flag-tajikistan',
		countryCode: '+992',
		isoCode: '762',
	},
	{
		label: 'Tanzania, United Republic of',
		code: 'TZ',
		capital: 'Dodoma',
		region: 'AF',
		currency: {
			code: 'TZS',
			label: 'Tanzanian shilling',
			symbol: 'Sh',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-tanzania',
		countryCode: '+255',
		isoCode: '834',
	},
	{
		label: 'Thailand',
		code: 'TH',
		capital: 'Bangkok',
		region: 'AS',
		currency: {
			code: 'THB',
			label: 'Thai baht',
			symbol: '฿',
		},
		language: {
			code: 'th',
			label: 'Thai',
		},
		iconFlagName: 'flag-thailand',
		countryCode: '+66',
		isoCode: '764',
	},
	{
		label: 'Timor-Leste',
		code: 'TL',
		capital: 'Dili',
		region: 'AS',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'pt',
			label: 'Portuguese',
		},
		iconFlagName: '',
		countryCode: '+670',
		isoCode: '626',
	},
	{
		label: 'Togo',
		code: 'TG',
		capital: 'Lomé',
		region: 'AF',
		currency: {
			code: 'XOF',
			label: 'West African CFA franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+228',
		isoCode: '768',
	},
	{
		label: 'Tokelau',
		code: 'TK',
		capital: 'Fakaofo',
		region: 'OC',
		currency: {
			code: 'NZD',
			label: 'New Zealand dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+690',
		isoCode: '772',
	},
	{
		label: 'Tonga',
		code: 'TO',
		capital: "Nuku'alofa",
		region: 'OC',
		currency: {
			code: 'TOP',
			label: 'Tongan paʻanga',
			symbol: 'T$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+676',
		isoCode: '776',
	},
	{
		label: 'Trinidad and Tobago',
		code: 'TT',
		capital: 'Port of Spain',
		region: 'SA',
		currency: {
			code: 'TTD',
			label: 'Trinidad and Tobago dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-trinidad-and-tobago',
		countryCode: '+1',
		isoCode: '780',
	},
	{
		label: 'Tunisia',
		code: 'TN',
		capital: 'Tunis',
		region: 'AF',
		currency: {
			code: 'TND',
			label: 'Tunisian dinar',
			symbol: 'د.ت',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+216',
		isoCode: '788',
	},
	{
		label: 'Turkey',
		code: 'TR',
		capital: 'Ankara',
		region: 'AS',
		currency: {
			code: 'TRY',
			label: 'Turkish lira',
			symbol: null,
		},
		language: {
			code: 'tr',
			label: 'Turkish',
		},
		iconFlagName: 'flag-turkey',
		countryCode: '+90',
		isoCode: '792',
	},
	{
		label: 'Turkmenistan',
		code: 'TM',
		capital: 'Ashgabat',
		region: 'AS',
		currency: {
			code: 'TMT',
			label: 'Turkmenistan manat',
			symbol: 'm',
		},
		language: {
			code: 'tk',
			label: 'Turkmen',
		},
		iconFlagName: '',
		countryCode: '+993',
		isoCode: '795',
	},
	{
		label: 'Turks and Caicos Islands',
		code: 'TC',
		capital: 'Cockburn Town',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+1',
		isoCode: '796',
	},
	{
		label: 'Tuvalu',
		code: 'TV',
		capital: 'Funafuti',
		region: 'OC',
		currency: {
			code: 'AUD',
			label: 'Australian dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+688',
		isoCode: '798',
	},
	{
		label: 'Uganda',
		code: 'UG',
		capital: 'Kampala',
		region: 'AF',
		currency: {
			code: 'UGX',
			label: 'Ugandan shilling',
			symbol: 'Sh',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+256',
		isoCode: '800',
	},
	{
		label: 'Ukraine',
		code: 'UA',
		capital: 'Kiev',
		region: 'EU',
		currency: {
			code: 'UAH',
			label: 'Ukrainian hryvnia',
			symbol: '₴',
		},
		language: {
			code: 'uk',
			label: 'Ukrainian',
		},
		iconFlagName: 'flag-ukraine',
		countryCode: '+380',
		isoCode: '804',
	},
	{
		label: 'United Arab Emirates',
		code: 'AE',
		capital: 'Abu Dhabi',
		region: 'AS',
		currency: {
			code: 'AED',
			label: 'United Arab Emirates dirham',
			symbol: 'د.إ',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: 'flag-united-arab-emirates',
		countryCode: '+971',
		isoCode: '784',
	},
	{
		label: 'United Kingdom of Great Britain and Northern Ireland',
		code: 'GB',
		capital: 'London',
		region: 'EU',
		currency: {
			code: 'GBP',
			label: 'British pound',
			symbol: '£',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-united-kingdom',
		countryCode: '+44',
		isoCode: '826',
	},
	{
		label: 'United Kingdom of Great Britain and Northern Ireland',
		code: 'UK',
		capital: 'London',
		region: 'EU',
		currency: {
			code: 'GBP',
			label: 'British pound',
			symbol: '£',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-united-kingdom',
		countryCode: '+44',
		isoCode: '826',
	},
	{
		label: 'United States of America',
		code: 'US',
		capital: 'Washington, D.C.',
		region: 'NA',
		currency: {
			code: 'USD',
			label: 'United States dollar',
			symbol: '$',
		},
		language: {
			code: 'en',
			iso639_2: 'eng',
			label: 'English',
			nativeName: 'English',
		},
		iconFlagName: 'flag-united-states',
		countryCode: '+1',
		isoCode: '840',
	},
	{
		label: 'Uruguay',
		code: 'UY',
		capital: 'Montevideo',
		region: 'SA',
		currency: {
			code: 'UYU',
			label: 'Uruguayan peso',
			symbol: '$',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-uruguay',
		countryCode: '+598',
		isoCode: '858',
	},
	{
		label: 'Uzbekistan',
		code: 'UZ',
		capital: 'Tashkent',
		region: 'AS',
		currency: {
			code: 'UZS',
			label: "Uzbekistani so'm",
			symbol: null,
		},
		language: {
			code: 'uz',
			label: 'Uzbek',
		},
		iconFlagName: 'flag-uzbekistan',
		countryCode: '+998',
		isoCode: '860',
	},
	{
		label: 'Vanuatu',
		code: 'VU',
		capital: 'Port Vila',
		region: 'OC',
		currency: {
			code: 'VUV',
			label: 'Vanuatu vatu',
			symbol: 'Vt',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: '',
		countryCode: '+678',
		isoCode: '548',
	},
	{
		label: 'Venezuela (Bolivarian Republic of)',
		code: 'VE',
		capital: 'Caracas',
		region: 'SA',
		currency: {
			code: 'VEF',
			label: 'Venezuelan bolívar',
			symbol: 'Bs F',
		},
		language: {
			code: 'es',
			label: 'Spanish',
		},
		iconFlagName: 'flag-venezuela',
		countryCode: '+58',
		isoCode: '862',
	},
	{
		label: 'Viet Nam',
		code: 'VN',
		capital: 'Hanoi',
		region: 'AS',
		currency: {
			code: 'VND',
			label: 'Vietnamese đồng',
			symbol: '₫',
		},
		language: {
			code: 'vi',
			label: 'Vietnamese',
		},
		iconFlagName: 'flag-vietnam',
		countryCode: '+84',
		isoCode: '704',
	},
	{
		label: 'Wallis and Futuna',
		code: 'WF',
		capital: 'Mata-Utu',
		region: 'OC',
		currency: {
			code: 'XPF',
			label: 'CFP franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+681',
		isoCode: '876',
	},
	{
		label: 'Wallis and Futuna',
		code: 'WF',
		capital: 'Mata-Utu',
		region: 'OC',
		currency: {
			code: 'XPF',
			label: 'CFP franc',
			symbol: 'Fr',
		},
		language: {
			code: 'fr',
			label: 'French',
		},
		iconFlagName: '',
		countryCode: '+681',
		isoCode: '876',
	},
	{
		label: 'Yemen',
		code: 'YE',
		capital: "Sana'a",
		region: 'AS',
		currency: {
			code: 'YER',
			label: 'Yemeni rial',
			symbol: '﷼',
		},
		language: {
			code: 'ar',
			label: 'Arabic',
		},
		iconFlagName: '',
		countryCode: '+967',
		isoCode: '887',
	},
	{
		label: 'Zambia',
		code: 'ZM',
		capital: 'Lusaka',
		region: 'AF',
		currency: {
			code: 'ZMW',
			label: 'Zambian kwacha',
			symbol: 'ZK',
		},
		language: {
			code: 'en',
			label: 'English',
		},
		iconFlagName: 'flag-zambia',
		countryCode: '+260',
		isoCode: '894',
	},
	{
		label: 'Zimbabwe',
		code: 'ZW',
		capital: 'Harare',
		region: 'AF',
		currency: {
			code: 'BWP',
			label: 'Botswana pula',
			symbol: 'P',
		},
		language: {
			code: 'en',
			iso639_2: 'eng',
			label: 'English',
			nativeName: 'English',
		},
		iconFlagName: '',
		countryCode: '+263',
		isoCode: '716',
	},
];
