/*
 * Purpose: Support code-generation activities with templates
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TemplateToken = {
	BANNER: '<% banner %>',
	IMPORTS: '<% imports %>',
	EXPORTS: '<% exports %>',
	TAG: '<% tag %>',
	ELEMENT_TYPES: '<% element-types %>',
	COMPONENT_CLASS_NAME: '<% component-class-name %>',
	COMPONENT_NAME: '<% component-name %>',
	TAG_PREFIX: '<% tag-prefix %>',
	PROP_TYPES: '<% prop-types %>',
	PROPS: '<% props %>',
	DEFAULT_PROPS: '<% default-props %>',
	PROPERTIES: '<% properties %>',
	ATTRIBUTES: '<% attributes %>',
	EVENTS: '<% events %>',
	CLASS_JSDOC: '<% jsdoc.class %>',
	TAG_DESCRIPTOR_JSON: '<% descriptor-json %>',
	COMPOUND_COMPONENTS: '<% compound-components %>',
	REACT_IMPORT: '<% react-import %>',
	REGISTRATION:
		/import { register<% component-name %> } from '@vonage\/vivid'\s+register<% component-name %>\('<% tag-prefix %>'\)/,
};

const GENERATED_CODE_BANNER = `/*
* DO NOT EDIT THIS FILE. IT IS GENERATED
*/`;
const templatesFolder = `${__dirname}`;
const getTemplate = (template, language) =>
	readFileSync(`${templatesFolder}/${language}/${template}.tmpl`, {
		encoding: 'utf8',
	}).replace(TemplateToken.BANNER, GENERATED_CODE_BANNER);

export { getTemplate, TemplateToken, GENERATED_CODE_BANNER };
