name: ✔️ Check Metadata

on:
  workflow_call:

jobs:
  check-metadata:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: '20.19.0'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Metadata
        run: pnpm turbo run @vonage/vivid#build

      - name: Check Components Metadata
        id: diff
        run: |
          echo 'DIFF_CONTENT<<EOF' >> "$GITHUB_OUTPUT"
          git --no-pager diff --exit-code ./libs/components/metadata.json >> "$GITHUB_OUTPUT" || true
          echo 'EOF' >> "$GITHUB_OUTPUT"

          git --no-pager diff --exit-code ./libs/components/metadata.json
        continue-on-error: true

      - uses: mshick/add-pr-comment@v2
        if: steps.diff.outcome == 'failure'
        with:
          allow-repeats: 'true'
          message: |
            :warning: The generated metadata has changed. Please update `libs/components/metadata.json` by running `pnpm turbo run @vonage/vivid#build` and committing the result.

            <details><summary>View Diff</summary>

            ```diff
            ${{ steps.diff.outputs.DIFF_CONTENT }}
            ```

            </details>

      - name: Fail if metadata is outdated
        if: steps.diff.outcome == 'failure'
        run: |
          echo "::error::metadata.json is outdated. Please run 'pnpm turbo run @vonage/vivid#build' and commit the updated file."
          exit 1
