name: 🚀 Publish Dart

on:
  workflow_call:
    inputs:
      sha:
        description: The revision to build and publish
        required: true
        type: string

  workflow_dispatch:

jobs:
  publish-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Pnpm setup
        uses: pnpm/action-setup@v4

      - name: Node Setup
        uses: actions/setup-node@v6
        with:
          node-version: '20.19.0'
          cache: 'pnpm'

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.35.0

      - name: Install Dependencies
        run: pnpm install

      - name: Setup pub
        run: dart pub token add https://eu-rtifactory.vonage.cloud/artifactory/api/pub/pub --env-var ARTIFACTORY_SECRET
        env:
          ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}

      - name: Build tokens
        working-directory: ./libs/design-tokens/
        run: pnpm run build

      - name: Set version
        working-directory: ./libs/design-tokens/flutter-dist
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          sed -i "s/^version:.*/version: $VERSION/" pubspec.yaml
          cat pubspec.yaml

      - name: Build and push package to Artifactory
        working-directory: ./libs/design-tokens/flutter-dist
        env:
          ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}
          PUB_HOSTED_URL: https://eu-artifactory.vonage.cloud/artifactory/api/pub/pub
        run: dart pub publish -f
