name: 🧪 Unit Test

on: workflow_call

jobs:
  call-test-chrome:
    uses: vonage/vivid-3/.github/workflows/_unit-test.yml@yinonov-build-action
    with:
      browser_name: chrome
      os: ubuntu-latest
      report_coverage: true

  call-test-safari:
    uses: vonage/vivid-3/.github/workflows/_unit-test.yml@yinonov-build-action
    with:
      browser_name: safari
      os: macos-latest
      report_coverage: false

  call-test-firefox:
    uses: vonage/vivid-3/.github/workflows/_unit-test.yml@yinonov-build-action
    with:
      browser_name: firefox
      os: ubuntu-latest
      report_coverage: false

  # visual-regression:
  #   runs-on: ubuntu-latest
  #   container: drizzt99/vonage:1.0.0
  #   env:
  #     GITHUB_TOKEN: ${{ github.token }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npm run build && ./scripts/visual-tests/run.tests.sh