name: '🧳 Upload Artifact'

on: workflow_call

jobs:
  upload:
    name: "Upload Build Artifact"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: public-artifact
          path: |
            package.json
            package-lock.json
            LICENSE.md
            dist
            .eleventy.js
            11ty
          if-no-files-found: error
