name: 📡 Upload coverage to Codecov

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: Operating System to run the workflow on
        default: 'ubuntu-latest'
        required: false
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    name: 'Upload coverage'
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: coverage
          path: ./coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          verbose: true
