name: 'Deploy doc to Deno'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'assets/**'
      - 'apps/docs/**'

jobs:
  deploy-deno:
    uses: vonage/vivid-3/.github/workflows/_deploy-deno.yml@main
