name: 🧬 Deploy

on:
  push:
    tags:
      - "deploy"
    branches:
      - 'main'

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-deploy-site:
    uses: vonage/vivid-3/.github/workflows/_deploy-deno.yml@main
