name: 'Lint PR Title'

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  lint-pr-title:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          requireScope: true
          subjectPattern: ^.*VIV-\d+.*$
          subjectPatternError: The PR title's description "{subject}" must contain a reference to the corresponding Jira ticket (VIV-xxx).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}