name: Post Merge Code Coverage

on:
  push:
    branches:
      - main

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  submit-main-code-coverage:
    uses: vonage/vivid-3/.github/workflows/_unit-test.yml@main
    with:
      os: ubuntu-latest
      report_coverage: true
