name: 🧬 Pre Release

on:
  push:
    branches: main

concurrency:
  group: ci-pre-release-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-lint:
    uses: vonage/vivid-3/.github/workflows/_lint.yml@main

  call-unit-tests:
    needs: call-lint
    uses: vonage/vivid-3/.github/workflows/_unit-test.yml@main
    with:
      os: ubuntu-latest
      report_coverage: true


  submit-code-coverage:
    needs: [call-unit-tests]
    name: "Code Coverage Submission"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage

      - uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          parallel: false
          github-token: ${{ github.token }}
          path-to-lcov: ./lcov.info
          flag-name: Tested on ubunti-latest / jsDOM

  call-visual-regression:
    needs: call-lint
    uses: vonage/vivid-3/.github/workflows/_visual-regression.yml@main

  call-publish-package:
    needs: [call-unit-tests, call-visual-regression]
    uses: vonage/vivid-3/.github/workflows/_publish-package.yml@main

  # ! temporary. site deployment should move to latest release
  call-deploy-site:
    needs: call-publish-package # do not deploy site if package is not published
    uses: vonage/vivid-3/.github/workflows/_deploy-deno.yml@main
